Repository alibaba/nacos, pull requests merged in 2018-11, with the labels that each got.

#158 Add more information in README.md to reflect the echosystem, fix [ISSUE #157],
  README.md
Labels: good first issue

#274 Fixes #272
  common/src/main/java/com/alibaba/nacos/common/util/SystemUtils.java
  common/src/test/java/com/alibaba/nacos/common/SystemUtilsTest.java
Labels: bug

#319 webpack adds hot dev mode
  console/src/main/resources/static/console-fe/build/webpack.base.conf.js
  console/src/main/resources/static/console-fe/build/webpack.dev.conf.js
  console/src/main/resources/static/console-fe/package.json
  console/src/main/resources/static/console-fe/src/index.js
  console/src/main/resources/static/css/main.8ecdd1f2.css
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.196fdd00.js
  console/src/main/resources/static/js/main.26f10b18.js
  console/src/main/resources/static/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
  console/src/main/resources/static/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  pom.xml
Labels: Nacos console, type/enhancement
