Repository alibaba/nacos, pull requests merged in 2019-01, with the labels that each got.

#559 #558 Add access log setting
  distribution/conf/application.properties
Labels: areas/log, size/XS

#548 refactor: SuccessDialog i18n #474
  console/src/main/resources/static/console-fe/src/components/SuccessDialog/SuccessDialog.js
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigSync/ConfigSync.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
Labels: areas/log, kind/refactor, size/M

#533 [ISSUE #202]format codes and correct comments for nacos-api
  api/src/main/java/com/alibaba/nacos/api/NacosFactory.java
  api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
  api/src/main/java/com/alibaba/nacos/api/cmdb/pojo/PreservedEntityTypes.java
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  api/src/main/java/com/alibaba/nacos/api/config/ConfigFactory.java
  api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java
  api/src/main/java/com/alibaba/nacos/api/config/convert/NacosConfigConverter.java
  api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigContext.java
  api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigFilter.java
  api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigFilterChain.java
  api/src/main/java/com/alibaba/nacos/api/config/filter/IConfigResponse.java
  api/src/main/java/com/alibaba/nacos/api/config/filter/IFilterConfig.java
  api/src/main/java/com/alibaba/nacos/api/config/listener/AbstractListener.java
  api/src/main/java/com/alibaba/nacos/api/config/listener/AbstractSharedListener.java
  api/src/main/java/com/alibaba/nacos/api/config/listener/Listener.java
  api/src/main/java/com/alibaba/nacos/api/naming/NamingFactory.java
  api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java
  api/src/main/java/com/alibaba/nacos/api/naming/listener/Event.java
  api/src/main/java/com/alibaba/nacos/api/naming/listener/EventListener.java
  api/src/main/java/com/alibaba/nacos/api/naming/listener/NamingEvent.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/Cluster.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/Instance.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/ListView.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/Service.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
Labels: size/XL

#582 Clean the code in config module
  client/src/main/java/com/alibaba/nacos/client/config/listener/impl/PropertiesListener.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/OpsController.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManagerMBean.java
  config/src/main/java/com/alibaba/nacos/config/server/service/BasicDataSourceServiceImpl.java
Labels: size/M

#589 Fixes #474 ConfigDetail
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console/src/main/resources/static/js/main.js
Labels: size/L

#594 Fixes #474 ConfigRollback
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigRollback/ConfigRollback.js
  console/src/main/resources/static/console-fe/yarn.lock
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: size/XXL

#596 config 获取客服端 ip 时添加 X-Forwarded-For 的支持
  config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/RequestUtilTest.java
  test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java
  test/src/test/java/com/alibaba/nacos/test/naming/RestAPI_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/ServiceListTest.java
Labels: size/L, size/M, size/XL

#597 Fixes #474 console fe project optimization && upgradin
  console/src/main/resources/static/console-fe/.babelrc
  console/src/main/resources/static/console-fe/package.json
  console/src/main/resources/static/console-fe/src/components/DeleteDialog/DeleteDialog.js
  console/src/main/resources/static/console-fe/src/components/DiffEditorDialog/DiffEditorDialog.js
  console/src/main/resources/static/console-fe/src/components/EditorNameSpace/EditorNameSpace.js
  console/src/main/resources/static/console-fe/src/components/NameSpaceList/NameSpaceList.js
  console/src/main/resources/static/console-fe/src/components/NewNameSpace/NewNameSpace.js
  console/src/main/resources/static/console-fe/src/components/RegionGroup/RegionGroup.js
  console/src/main/resources/static/console-fe/src/components/ShowCodeing/ShowCodeing.js
  console/src/main/resources/static/console-fe/src/components/SuccessDialog/SuccessDialog.js
  console/src/main/resources/static/console-fe/src/constants.js
  console/src/main/resources/static/console-fe/src/index.js
  console/src/main/resources/static/console-fe/src/layouts/Header.js
  console/src/main/resources/static/console-fe/src/layouts/MainLayout.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigRollback/ConfigRollback.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigSync/ConfigSync.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/DashboardCard.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/HistoryDetail/HistoryDetail.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console/src/main/resources/static/console-fe/src/pages/NameSpace/NameSpace.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/EditClusterDialog.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/EditInstanceDialog.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/EditServiceDialog.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/InstanceTable.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceDetail/ServiceDetail.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceList/ServiceList.js
  console/src/main/resources/static/console-fe/src/reducers/locale.js
  console/src/main/resources/static/console-fe/yarn.lock
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: size/XXL

#607 fix #499
  console/src/main/resources/static/console-fe/src/index.js
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: Nacos console

#593 Feature metrics
  client/pom.xml
  client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
  client/src/main/java/com/alibaba/nacos/client/config/http/HttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java
  client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
  config/pom.xml
  config/src/main/java/com/alibaba/nacos/config/server/Config.java
  config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
  config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/MemoryMonitor.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/MetricsMonitor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/BasicDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ServerListService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java
  console/src/main/java/com/alibaba/nacos/Nacos.java
  distribution/conf/application.properties
  naming/pom.xml
  naming/src/main/java/com/alibaba/nacos/naming/NamingApp.java
  naming/src/main/java/com/alibaba/nacos/naming/core/DomainsManager.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HttpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/MysqlHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/TcpSuperSenseProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
  naming/src/main/java/com/alibaba/nacos/naming/raft/RaftCore.java
  naming/src/main/java/com/alibaba/nacos/naming/raft/RaftStore.java
  pom.xml
  test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_ITCase.java
Labels: kind/feature, size/XXL
