Repository alibaba/nacos, pull requests merged in 2020-09, with the labels that each got.

#3721 Fix Logging in with the wrong username or password will cause jackson serialization results to fail
  common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
Labels: kind/bug

#3716 [ISSUE#3712] add apache http client factory
  common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpMethod.java
  common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
Labels: kind/enhancement

#3742 gzip support; using object list instead of string concat for batch listen config
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeBatchListenResponse.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/RsocketUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
Labels: kind/feature

#3744 [ISSUE#3692] Use new distro implmentation to handle init all datum request.
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/DistroProtocol.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroComponentHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroDataStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroTransportAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/exception/DistroException.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/task/load/DistroLoadDataTask.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java
Labels: kind/refactor

#3749 optimize request /header /meta info model, uniform request resolver pattern.
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectionSetupRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestMeta.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ServerPushResponse.java
  api/src/main/proto/nacos_grpc_service.proto
  client/src/main/java/com/alibaba/nacos/client/config/http/HttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  common/src/main/java/com/alibaba/nacos/common/remote/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/RsocketUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  console/src/main/java/com/alibaba/nacos/Nacos.java
  core/src/main/java/com/alibaba/nacos/core/monitor/MetricsMonitor.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/grpc/GrpcClient.java
  test/src/test/java/com/alibaba/nacos/test/core/RsocketClientTest.java
Labels: kind/feature

#3751 client switch server bugfix ; cluster server connection manage ； loader balance with specific server ip
  api/src/main/java/com/alibaba/nacos/api/remote/request/ServerLoaderInfoRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ServerLoaderInfoResponse.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/core/HeartBeatRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/core/RemoteConnectionEventListener.java
  core/src/main/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
Labels: kind/feature

#3752 loader balance basic support: adjust loader count once and up limit ；switch single client
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  pom.xml
Labels: kind/feature

#3750 [ISSUE#3658] Move distro sync code to nacos-core module
  consistency/src/main/java/com/alibaba/nacos/consistency/DataOperation.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroProtocol.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroCallback.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroComponentHolder.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroDataProcessor.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroDataStorage.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroFailedTaskHandler.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroTransportAgent.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/entity/DistroData.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/entity/DistroKey.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/exception/DistroException.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/DistroTaskEngineHolder.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/delay/DistroDelayTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/delay/DistroDelayTaskExecuteEngine.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/delay/DistroDelayTaskProcessor.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/AbstractDistroExecuteTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroExecuteWorker.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroExecuteWorkersManager.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroSyncChangeTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyTask.java
  core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java
  core/src/main/java/com/alibaba/nacos/core/utils/Loggers.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpData.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpCombinedKey.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpCombinedKeyDelayTask.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpCombinedKeyExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpCombinedKeyTaskFailedHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/combined/DistroHttpDelayTaskProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/newimpl/component/DistroDataStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java
Labels: kind/refactor

#3772 [ISSUE #3770] replace the deprecated api com.fasterxml.jackson.databind.node.ObjectNode#put(java.lang.String, com.fasterxml.jackson.databind.JsonNode)
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ApiController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
Labels: kind/refactor

#3765 [ISSUE #3658] Some enhance refactor for naming distro
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpData.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpRegistry.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java
Labels: kind/refactor

#3788 Refactor singleton naming with new naming model design
  core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/ClusterClient.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/ClusterClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/grpc/GrpcClusterClient.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/grpc/SingleServerListFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/request/ForwardHeartBeatRequest.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/request/ForwardInstanceRequest.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientOperationEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/RemotePushService.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnectionHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ForwardHeartBeatRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ForwardInstanceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/InstanceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/task/RenewInstanceBeatTask.java
Labels: kind/feature

#3767 [ISSUE #3687] check serviceName's format(groupName@@serviceName) in server and client
  api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
Labels: kind/bug

#3789 Update ConvertUtils.java
  common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java
Labels: kind/code quality

#3795 Adapt query service list request with new model
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java
  naming/src/main/java/com/alibaba/nacos/naming/push/RemotePushService.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceListRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/feature

#3797 optmize rpc client lifecycle ；request timeout to rpc client； some bugfix
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientStatus.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
Labels: kind/feature

#3808 optimize dumpService warning on starting up ； async request suppport in cluster rpc client proxy.
  api/src/main/java/com/alibaba/nacos/api/remote/RemoteConstants.java
  api/src/main/java/com/alibaba/nacos/api/remote/Requester.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/constant/HttpHeaderConsts.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/ExternalDumpService.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/ClusterConnection.java
  pom.xml
Labels: kind/feature

#3816 [ISSUE#3787] fix ConvertUtils can not handle FormatException.
  common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java
Labels: kind/bug

#3821 ak auth support on long connection
  address/src/main/java/com/alibaba/nacos/address/auth/AddressServerAuthManager.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigQueryResponse.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/response/ServiceListResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
  auth/src/main/java/com/alibaba/nacos/auth/AuthManager.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/utils/ReflectUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfiRemoveRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
  core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestFilter.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestFilters.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java
Labels: kind/feature

#3825 Add ip port client and manager
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroProtocol.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientComponentRegistry.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnection.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnectionHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceQueryRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/feature

#3763 [ISSUE#3192] naming module replace http client
  common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpMethod.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
  common/src/main/java/com/alibaba/nacos/common/http/client/NacosAsyncRestTemplate.java
  common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
  common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/client/request/JdkHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
  common/src/main/java/com/alibaba/nacos/common/model/RequestHttpEntity.java
  common/src/main/java/com/alibaba/nacos/common/utils/HttpMethod.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTask.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftPeerSet.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckCommon.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/ServerStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/ServiceStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java
Labels: kind/refactor

#3835 [ISSUE#3833] Fix NullPointerException when no subscriber for slow event
  common/src/main/java/com/alibaba/nacos/common/notify/DefaultSharePublisher.java
  common/src/test/java/com/alibaba/nacos/common/notify/NotifyCenterTest.java
Labels: kind/enhancement

#3837 Set mediaType charset as utf8
  common/src/main/java/com/alibaba/nacos/common/http/param/MediaType.java
Labels: kind/bug

#3849 Add upd push for ip port client
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
  naming/src/main/java/com/alibaba/nacos/naming/push/ClientPushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecuteService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecuteServiceDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/RpcPushExecuteServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/UdpPushExecuteServiceImpl.java
Labels: kind/feature

#3864 Refactor Instance Controller
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java
  naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/pojo/SubscriberTest.java
Labels: kind/refactor

#3872 [ISSUE #3867] replace the way which get version
  api/src/main/resources/application.properties
  client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
  client/src/main/resources/application.properties
Labels: kind/bug

#3883 [ISSUE #3815]Fix chinese string are truncated in ConcunrrentDiskUtil
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java
  client/src/test/java/com/alibaba/nacos/client/naming/cache/DiskCacheTest.java
Labels: kind/bug

#3900 [ISSUE #3899]Update springboot version
  pom.xml
Labels: dependencies

#3891 [ISSUE #3781]Fix service list intermittently lost service
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java
Labels: kind/bug
