Repository alibaba/nacos, pull requests merged in 2020-07, with the labels that each got.

#3229 [ISSUE #3223] Upgrade log4j to security version
  client/pom.xml
  pom.xml
Labels: dependencies, java

#3242 [ISSUE #2992] Use new code style for nacos-cmdb module.
  cmdb/pom.xml
  cmdb/src/main/java/com/alibaba/nacos/cmdb/CmdbApp.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/controllers/OperationController.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/core/CmdbManager.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/core/SwitchAndOptions.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/memory/CmdbProvider.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/service/CmdbReader.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/service/CmdbWriter.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/Loggers.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/UtilsAndCommons.java
  cmdb/src/main/resources/application.properties
Labels: kind/code quality

#3239 [ISSUE #2992] Use new code style for nacos-address module.
  address/pom.xml
  address/src/main/java/com/alibaba/nacos/address/AddressServer.java
  address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java
  address/src/main/java/com/alibaba/nacos/address/component/AddressServerManager.java
  address/src/main/java/com/alibaba/nacos/address/constant/AddressServerConstants.java
  address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java
  address/src/main/java/com/alibaba/nacos/address/controller/ServerListController.java
  address/src/main/java/com/alibaba/nacos/address/misc/Loggers.java
  address/src/main/java/com/alibaba/nacos/address/util/AddressServerParamCheckUtil.java
  address/src/main/resources/META-INF/logback/nacos-included.xml
  address/src/main/resources/application.properties
  address/src/test/java/com/alibaba/nacos/address/AddressServerControllerTests.java
  address/src/test/java/com/alibaba/nacos/address/ParamCheckUtilTests.java
  address/src/test/java/com/alibaba/nacos/address/SimpleHttpTestUtils.java
Labels: kind/code quality

#3236 optimize isExistTable function
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
Labels: pending

#3250 Resolve the issues of codestyle of nacos-config module for phase1
  config/src/main/java/com/alibaba/nacos/config/server/Config.java
  config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java
  config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/PermissionInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/PermissionPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/RoleInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/RolePersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/UserPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/configuration/ConditionOnEmbeddedStorage.java
  config/src/main/java/com/alibaba/nacos/config/server/configuration/ConditionOnExternalStorage.java
  config/src/main/java/com/alibaba/nacos/config/server/configuration/ConditionStandaloneEmbedStorage.java
  config/src/main/java/com/alibaba/nacos/config/server/constant/Constants.java
  config/src/main/java/com/alibaba/nacos/config/server/constant/CounterMode.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
Labels: kind/code quality

#3253 Resolve the issues of codestyle of nacos-config module for phase2
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpConfigHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/EmbeddedDumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/ExternalDumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllBetaProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllTagProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpChangeProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpAllBetaTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpAllTagTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpAllTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpChangeTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeDataTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeDatumService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeTaskProcessor.java
Labels: kind/code quality

#3259 Resolve the issues of codestyle of nacos-config module for phase3
  config/src/main/java/com/alibaba/nacos/config/server/controller/parameters/SameNamespaceCloneConfigBean.java
  config/src/main/java/com/alibaba/nacos/config/server/enums/FileTypeEnum.java
  config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/exception/NJdbcException.java
  config/src/main/java/com/alibaba/nacos/config/server/exception/NacosConfigException.java
  config/src/main/java/com/alibaba/nacos/config/server/filter/CurcuitFilter.java
  config/src/main/java/com/alibaba/nacos/config/server/filter/NacosWebFilter.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/AbstractTask.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManagerMBean.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/model/AclInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/AuthType.java
  config/src/main/java/com/alibaba/nacos/config/server/model/CacheItem.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigAdvanceInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigAllInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigHistoryInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfo4Beta.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfo4Tag.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoAggr.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBase.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBaseEx.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoBetaWrapper.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoChanged.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoEx.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoTagWrapper.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigInfoWrapper.java
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigKey.java
  config/src/main/java/com/alibaba/nacos/config/server/model/GroupInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/GroupkeyListenserStatus.java
  config/src/main/java/com/alibaba/nacos/config/server/model/HistoryContext.java
  config/src/main/java/com/alibaba/nacos/config/server/model/Page.java
  config/src/main/java/com/alibaba/nacos/config/server/model/RestPageResult.java
  config/src/main/java/com/alibaba/nacos/config/server/model/SameConfigPolicy.java
  config/src/main/java/com/alibaba/nacos/config/server/model/SampleResult.java
  config/src/main/java/com/alibaba/nacos/config/server/model/SubInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/SubscriberStatus.java
  config/src/main/java/com/alibaba/nacos/config/server/model/TenantInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/User.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationPublishRecord.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/GroupKey.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/MonitorInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/capacity/Capacity.java
  config/src/main/java/com/alibaba/nacos/config/server/model/capacity/GroupCapacity.java
  config/src/main/java/com/alibaba/nacos/config/server/model/capacity/TenantCapacity.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/ConfigDataChangeEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/ConfigDumpEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/DerbyLoadEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/LocalDataChangeEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/RaftDBErrorEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/RaftDBErrorRecoverEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ClientIpWhiteList.java
Labels: kind/code quality

#3260 Hotfix double register null service and beat info invalid problem
  client/pom.xml
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
  client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  client/src/test/java/com/alibaba/nacos/client/NamingTest.java
Labels: kind/bug

#3267 Hotfix register null cluster name instance problem
  common/src/main/java/com/alibaba/nacos/common/constant/HttpHeaderConsts.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
  common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
  common/src/test/java/com/alibaba/nacos/common/http/param/QueryTest.java
Labels: kind/bug

#3279 Hotfix default mysql config
  console/src/main/resources/META-INF/nacos-default.properties
Labels: kind/bug

#3287 Hotfix send beat info error
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
Labels: kind/bug

#3289 [ISSUE #2992] Use new code style for nacos-cmdb module.
  common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
  common/src/main/java/com/alibaba/nacos/common/http/handler/ResponseHandler.java
  common/src/test/java/com/alibaba/nacos/common/notify/NotifyCenterTest.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/notify/DefaultPublisher.java
  core/src/main/java/com/alibaba/nacos/core/utils/DiskUtils.java
  istio/pom.xml
  istio/src/main/java/com/alibaba/nacos/istio/IstioApp.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/CollectionTypes.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/McpServerIntercepter.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpServer.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java
  istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java
  istio/src/main/java/com/alibaba/nacos/istio/misc/Loggers.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
  pom.xml
Labels: kind/code quality

#3290 [ISSUE #3249] Use new code style for nacos-config module/test.
  config/pom.xml
  config/src/test/java/com/alibaba/nacos/config/server/configuration/LocalDataSourceConfigurationTest.java
  config/src/test/java/com/alibaba/nacos/config/server/constant/ConstantsTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerUnitTest.java
  config/src/test/java/com/alibaba/nacos/config/server/model/ConfigInfoTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/AggrWhitelistTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ClientTrackServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/DiskServiceUnitTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/RowMapperManagerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourcePropertiesTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/DerbyUtilsTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/GroupKeyTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/RequestUtilTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/SimpleReadWriteLockTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/event/EventDispatcherTest.java
  config/src/test/resources/log4j.properties
  config/src/test/resources/user.properties
Labels: kind/code quality

#3293 [ISSUE #2992]Recheck all checkstyle and open checkstyle during building
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  config/src/main/java/com/alibaba/nacos/config/server/filter/CurcuitFilter.java
  config/src/main/java/com/alibaba/nacos/config/server/model/SameConfigPolicy.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/RaftDbErrorEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/RaftDbErrorRecoverEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/PrintMemoryTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DataSourceService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/task/DumpTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  example/src/main/java/com/alibaba/nacos/example/App.java
  example/src/main/java/com/alibaba/nacos/example/ConfigExample.java
  example/src/main/java/com/alibaba/nacos/example/NamingExample.java
  example/src/test/java/com/alibaba/nacos/example/AppTest.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/CollectionTypes.java
  style/NacosCheckStyle.xml
  test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java
  test/src/test/java/com/alibaba/nacos/test/core/BaseClusterTest.java
Labels: kind/code quality

#3299 Update BeatReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
Labels: kind/code quality

#3198 [ISSUE #3197] NacosRestTemplate enhance
  common/src/main/java/com/alibaba/nacos/common/http/client/DefaultHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/client/HttpClientRequestInterceptor.java
  common/src/main/java/com/alibaba/nacos/common/http/client/InterceptingHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java
  common/src/main/java/com/alibaba/nacos/common/model/RequestHttpEntity.java
  test/src/test/java/com/alibaba/nacos/test/common/NacosAsyncRestTemplate_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_Interceptors_ITCase.java
Labels: area/Nacos Core, kind/refactor

#3310 [ISSUE#3179]Remove original NotifyCenter codes in the core module.
  core/src/main/java/com/alibaba/nacos/core/notify/DefaultPublisher.java
  core/src/main/java/com/alibaba/nacos/core/notify/Event.java
  core/src/main/java/com/alibaba/nacos/core/notify/EventPublisher.java
  core/src/main/java/com/alibaba/nacos/core/notify/NotifyCenter.java
  core/src/main/java/com/alibaba/nacos/core/notify/SlowEvent.java
  core/src/main/java/com/alibaba/nacos/core/notify/listener/SmartSubscribe.java
  core/src/main/java/com/alibaba/nacos/core/notify/listener/Subscribe.java
Labels: area/Nacos Core, kind/refactor

#3206 [ISSUE #2856]Adjust the use of thread pools (config module)
  cmdb/src/main/java/com/alibaba/nacos/cmdb/memory/CmdbProvider.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/CmdbExecutor.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/utils/UtilsAndCommons.java
  common/src/main/java/com/alibaba/nacos/common/executor/ExecutorFactory.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/MemoryMonitor.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/NotifyTaskQueueMonitorTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleFlowData.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleIpFlowData.java
Labels: area/Nacos Core, kind/refactor

#3313 Replace original EventDispatcher with NotifyCenter in the config module.
  config/src/main/java/com/alibaba/nacos/config/server/model/event/ConfigDataChangeEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/LocalDataChangeEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigChangePublisher.java
  config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeTaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java
Labels: kind/refactor

#3322 [ISSUE##3317]Change the http client implementation that nacos resttemplate depends on from apache to JDk
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java
  common/src/main/java/com/alibaba/nacos/common/http/client/HttpClientResponse.java
  common/src/main/java/com/alibaba/nacos/common/http/client/JdkHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/client/JdkHttpClientResponse.java
Labels: kind/refactor

#3319 [ISSUE##2859]Remove original EventDispatcher in the config module.
  config/src/main/java/com/alibaba/nacos/config/server/utils/event/EventDispatcher.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/event/EventDispatcherTest.java
Labels: kind/refactor

#3343 Add naming support gRPC for register and deregister instance
  api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/request/InstanceRequest.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/request/NamingCommonRequest.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/response/InstanceResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
  client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingGrpcClientProxy.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/InstanceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/SubscribeServiceRequestHandler.java
Labels: area/Naming, kind/feature

#3363 [ISSUE#3356]Fix no throw exception when publish event but no subsciber.
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
  common/src/test/java/com/alibaba/nacos/common/notify/NotifyCenterTest.java
Labels: kind/bug

#3365 client reconnection optimize
  api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
  client/src/main/java/com/alibaba/nacos/client/remote/RpcClientStatus.java
  client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
Labels: area/Config, kind/feature

#3367 [ISSUE #1097] client reconnect optimize, combine first time start and reconnect code
  client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
  client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
Labels: area/Nacos Core, kind/feature

#3348 [ISSUE #3224]nacos-client module http client replace
  client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
  client/src/main/java/com/alibaba/nacos/client/config/http/HttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/HttpSimpleClient.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/SpasAdapter.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
  client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
  client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
  common/src/main/java/com/alibaba/nacos/common/http/client/JdkHttpClientResponse.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_CITCase.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_CITCase.java
Labels: java, kind/refactor

#3374 Hotfix client sdk depend jdk7 charset.
  client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
Labels: kind/bug

#3376 Hotfix client sdk depend jdk7 charset.
  client/src/main/java/com/alibaba/nacos/client/identify/Base64.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/SignUtil.java
Labels: kind/bug

#3387 [ISSUE #3386] Extract `NamingClientProxy` Interface
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushResponseHandler.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/HttpClient.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
  client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
  client/src/test/java/com/alibaba/nacos/client/BeatReactorTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/HostReactorTest.java
  test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java
  test/src/test/java/com/alibaba/nacos/test/naming/NamingHttpClientProxy_ITCase.java
Labels: area/Naming, kind/refactor

#3389 [ISSUE #3386] Extract server list maintain logic to ServerListManager
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/NamingHttpUtil.java
Labels: area/Naming, kind/refactor

#3371 [ISSUE #3370] Issue with executing shell script /bin/sh^M on Unix/Linux
  distribution/release-nacos.xml
Labels: kind/enhancement, os/windows

#3394 [ISSUE #3386] Move BeatReactor into HttpClientProxy
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushResponseHandler.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/HostReactorTest.java
Labels: area/Naming, kind/refactor

#3402 [ISSUE #3386] Refactor HostReactor.java to ServiceInfoHolder and ServiceInfoUpdateService
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushResponseHandler.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/HostReactorTest.java
  test/src/test/java/com/alibaba/nacos/test/naming/AutoDeregisterInstance_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/MultiTenant_InstanceAPI_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/utils/NamingTestUtils.java
Labels: area/Naming, kind/feature

#3405 notify connect listeners on start up
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigPublishRequest.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
  client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
Labels: area/Nacos Core, kind/feature

#3407 [ISSUE #1097] Remove naming context when grpc connection close.
  api/src/main/java/com/alibaba/nacos/api/naming/remote/response/NotifySubscriberResponse.java
  core/src/main/java/com/alibaba/nacos/core/remote/AsyncListenContext.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/DataChangeListenerNotifier.java
  naming/src/main/java/com/alibaba/nacos/naming/push/RemotePushService.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnection.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnectionHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/InstanceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java
Labels: area/Naming, kind/feature

#3425 [ISSUE #1097]grpc support all namingService api
  api/src/main/java/com/alibaba/nacos/api/naming/remote/NamingRemoteConstants.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/request/ServiceListRequest.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/response/ServiceListResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ServiceListRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
  naming/src/test/java/com/alibaba/nacos/naming/utils/ServiceUtilTest.java
Labels: area/Naming, kind/feature

#3449 [ISSUE #3428] Fix token valid go login bug
  console/src/main/resources/static/console-fe/src/globalLib.js
  console/src/main/resources/static/console-fe/src/utils/request.js
Labels: area/Nacos console, kind/bug

#3442 [#3388]Reset nacos roles, permissions during reloading role info from database
  console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
Labels: area/Nacos console, kind/bug

#3427 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/old-issue-template.md
Labels: kind/proposal

#3469 Fix the thread safety problem of obtaining HttpRequestBase through BaseHttpMethod enumeration
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpMethod.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
  common/src/main/java/com/alibaba/nacos/common/http/client/request/DefaultHttpClientRequest.java
Labels: kind/bug

#3478 Add gprc support-> add server push ack
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeListenRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigRequestTypeConstants.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeBatchListenResponse.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeListenResponse.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigResponseTypeConstants.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/response/NotifySubscriberResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/ResponseRegistry.java
  api/src/main/java/com/alibaba/nacos/api/remote/connection/Connection.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/PushAckRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestTypeConstants.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ConnectResetResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/PushCallBack.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ServerPushResponse.java
  api/src/main/proto/nacos_grpc_service.proto
  client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/remote/ConnectionEventListener.java
  client/src/main/java/com/alibaba/nacos/client/remote/RpcClient.java
  client/src/main/java/com/alibaba/nacos/client/remote/grpc/GrpcClient.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeNotifier.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcAckSynchronizer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestHandlerReactor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/push/RemotePushService.java
Labels: area/Nacos Core, kind/feature

#3481 move rpc client from client to common and move request response to api ; solve conflict.
  api/src/main/java/com/alibaba/nacos/api/remote/request/HeartBeatRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestMeta.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestTypeConstants.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/HeartBeatResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/PlainBodyResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ResponseCode.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ResponseTypeConstants.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/UnKnowResponse.java
  api/src/main/java/com/alibaba/nacos/api/utils/NetUtils.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/remote/ConfigGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListener.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushResponseHandler.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/NamingHttpUtil.java
  client/src/main/java/com/alibaba/nacos/client/utils/ClientCommonUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ConnectionEventListener.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ResponseRegistry.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientStatus.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ServerListFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ServerPushResponseHandler.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/exception/ConnectionAlreadyClosedException.java
  common/src/main/java/com/alibaba/nacos/common/remote/exception/RemoteException.java
  common/src/main/java/com/alibaba/nacos/common/utils/VersionUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListener.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMetaInfo.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionType.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcStreamRequestHanderImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/ClusterConnection.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/grpc/GrpcClient.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnection.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnectionHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/ForwardInstanceRequestHandler.java
Labels: area/Nacos Core, kind/feature

#3456 [ISSUE#3091] Fix address server can't start up by implement an empty auth manager.
  address/src/main/java/com/alibaba/nacos/address/auth/AddressServerAuthManager.java
  address/src/main/java/com/alibaba/nacos/address/configuration/AddressServerSpringConfiguration.java
Labels: kind/bug

#3470 [#1839]add ContentType return while getConfig
  common/src/main/java/com/alibaba/nacos/common/http/param/MediaType.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/enums/FileTypeEnum.java
Labels: kind/enhancement
