Repository alibaba/nacos, pull requests merged in 2020-10, with the labels that each got.

#3859 [ISSUE#3533] change cache dir with namespace -- part 1
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
Labels: kind/enhancement

#3882 [ISSUE#3533] change cache dir with namespace -- part 2
  client/src/main/java/com/alibaba/nacos/client/logging/AbstractNacosLogging.java
  client/src/main/resources/nacos-log4j2.xml
  client/src/main/resources/nacos-logback.xml
Labels: kind/enhancement, kind/feature

#3970 ak auth support;log optimize; client port aware on server side
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/BiRequestStreamGrpc.java
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/Metadata.java
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/MetadataOrBuilder.java
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/NacosGrpcService.java
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/RequestGrpc.java
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/RequestStreamGrpc.java
  api/src/main/java/com/alibaba/nacos/api/remote/RequestCallBack.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestMeta.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestTypeConstants.java
  api/src/main/proto/nacos_grpc_service.proto
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingPushResponseHandler.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ServerRequestHandler.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketUtils.java
  common/src/main/resources/nacos-log4j2.xml
  common/src/main/resources/nacos-logback.xml
  config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/MetricsMonitor.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/NotifyTaskQueueMonitorTask.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigClusterRpcClientProxy.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  core/src/main/java/com/alibaba/nacos/core/remote/AbstractRequestFilter.java
  core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMetaInfo.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestHandlerRegistry.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/core/RpcAckCallbackInitorOrCleaner.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnection.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/RemotingConnectionHolder.java
Labels: kind/feature

#3956 [ISSUE-#3955] Fix com.alibaba.nacos.naming.controllers.ClusterControllerTest can't pass
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java
Labels: area/Test

#3974 Fix#3973
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/NamespaceUtil.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/NamespaceUtilTest.java
Labels: kind/bug

#3982 [ISSUE#3384] Fix member extend info do not update error.
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberMetaDataConstants.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtils.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilsTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
Labels: area/Nacos Core, kind/bug

#3984 Fix issue 2866
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
Labels: kind/enhancement, kind/user experience

#3985 [ISSUE #3576] [Enhancement] Adding the destroy lifecycle method on NamingMaintainService
  api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  test/src/test/java/com/alibaba/nacos/test/naming/NamingMaintainService_ITCase.java
Labels: kind/enhancement

#3999 [ISSUE#3992] Revert "for #3621 (#3668)" to fix issue 3992.
  client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
Labels: kind/bug

#3988 [ISSUE-#3855] Provided a feature to view version comparisons in the configDetails page
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  console/src/main/resources/static/console-fe/src/components/DiffEditorDialog/DiffEditorDialog.js
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigDetail/index.scss
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console/src/main/resources/static/console-fe/test/sample/configDetail.spec.js
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/feature

#4019 For #3710#, Fix special characters cannot be used in Metadata
  core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java
Labels: kind/bug

#3912 [ISSUE #3904] feature - operate instance's metadata alonely
  api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
  common/src/main/java/com/alibaba/nacos/common/utils/MapUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationContext.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/InstanceOperationInfo.java
  naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
Labels: kind/feature

#4021 [ISSUE #4022] Modify the startup script custom configuration first default configur…
  distribution/bin/startup.cmd
  distribution/bin/startup.sh
Labels: kind/bug

#4043 Refine GoClient value
  naming/src/main/java/com/alibaba/nacos/naming/push/ClientInfo.java
Labels: go

#4099 Async some time-consuming operation and add metadata
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceInfoGenerator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ClusterMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NacosNamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/HeartBeatInstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatUpdateTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckCommon.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/NamingExecuteTaskDispatcher.java
  naming/src/main/java/com/alibaba/nacos/naming/push/ClientPushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTask.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/web/DistroTagGeneratorImpl.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskV2Test.java
Labels: kind/enhancement
