Repository alibaba/nacos, pull requests merged in 2020-11, with the labels that each got.

#4112 Use interceptors and checkers to refactor client beat check task
  common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/NacosHealthCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/AbstractBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/BeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/BeatProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatProcessorV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatUpdateTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatCheckTaskInterceptorChain.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ServiceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/interceptor/AbstractHealthCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckEnableInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckInterceptorChain.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckResponsibleInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapper.java
  naming/src/main/java/com/alibaba/nacos/naming/interceptor/Interceptable.java
  naming/src/main/java/com/alibaba/nacos/naming/interceptor/NacosNamingInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/interceptor/NacosNamingInterceptorChain.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapperTest.java
Labels: kind/refactor

#4095 Reduce unnecessary InetAddress.getLocalHost() calls
  core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
Labels: kind/code quality

#4122 [ISSUE#3831]Delete the old http client code
  client/src/main/java/com/alibaba/nacos/client/config/impl/HttpSimpleClient.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/HttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientManager.java
  common/src/main/java/com/alibaba/nacos/common/http/NAsyncHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NSyncHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NacosAsyncHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NacosSyncHttpClient.java
  core/src/main/java/com/alibaba/nacos/core/code/StartingSpringApplicationRunListener.java
  core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
Labels: kind/code quality

#4131 fix the occasional failure of CI
  .travis.yml
  pom.xml
Labels: area/Test

#4150 [ISSUE#3832] add common http client shutdown method
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java
Labels: kind/refactor

#4151 Add NacosServiceLoader and replace ServiceLoader usage directly
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigChangeHandler.java
  cmdb/src/main/java/com/alibaba/nacos/cmdb/memory/CmdbProvider.java
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
  common/src/main/java/com/alibaba/nacos/common/spi/NacosServiceLoader.java
  common/src/main/java/com/alibaba/nacos/common/spi/ServiceLoaderException.java
  common/src/test/java/com/alibaba/nacos/common/spi/NacosServiceLoaderTest.java
  common/src/test/java/com/alibaba/nacos/common/spi/SpiTestImpl.java
  common/src/test/java/com/alibaba/nacos/common/spi/SpiTestInterface.java
  common/src/test/resources/META-INF/services/com.alibaba.nacos.common.spi.SpiTestInterface
  consistency/src/main/java/com/alibaba/nacos/consistency/SerializeFactory.java
  core/src/main/java/com/alibaba/nacos/core/distributed/ConsistencyConfiguration.java
  core/src/main/java/com/alibaba/nacos/core/distributed/id/IdGeneratorManager.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/extend/HealthCheckExtendProvider.java
Labels: kind/refactor

#3915 [ISSUE #3907] when publishConfig, if type is absent, set default value 'text'
  api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java
  api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
  client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
Labels: kind/enhancement

#4165 [ISSUE #3102] Create utils class to nacos-common
  common/src/main/java/com/alibaba/nacos/common/utils/ArrayUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/BooleanUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java
  common/src/main/java/com/alibaba/nacos/common/utils/NumberUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/RandomUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
Labels: dependencies

#4178 For #3607, #4078, #4170, Datasource pool configuration can be configured.
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/DataSourcePoolProperties.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java
  config/src/test/java/com/alibaba/nacos/config/server/service/datasource/DataSourcePoolPropertiesTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourcePropertiesTest.java
  config/src/test/resources/jdbc.properties
  distribution/conf/application.properties
Labels: kind/enhancement

#4186 [ISSUE-#4179] Add index for db.user and db.password
  console/src/main/resources/application.properties
  distribution/conf/application.properties
  distribution/conf/application.properties.example
Labels: kind/user experience

#4194 Fix issue 4187
  core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
  core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java
Labels: kind/bug

#4204 Feature support grpc core
  address/pom.xml
  api/pom.xml
  auth/pom.xml
  client/pom.xml
  cmdb/pom.xml
  common/pom.xml
  config/pom.xml
  consistency/pom.xml
  console/pom.xml
  core/pom.xml
  distribution/pom.xml
  example/pom.xml
  istio/pom.xml
  naming/pom.xml
  naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ServiceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapperTest.java
  pom.xml
  sys/pom.xml
  test/pom.xml
Labels: kind/feature

#4203 [ISSUE-#4181] Fix errors related to custom contextPath
  core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
  sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java
  test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCacheTest.java
Labels: kind/bug

#4217 更新版本；集群整体重新负载均衡功能；变更推送内容；推送SLA日志；常量池改造；启动时长链接优化；删除rpc digest 日志
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeNotifyRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/ServerReloadRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ServerReloadResponse.java
  client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
  client/src/main/resources/nacos-logback.xml
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketUtils.java
  common/src/main/resources/nacos-log4j2.xml
  common/src/main/resources/nacos-logback.xml
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/LocalDataChangeEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfiRemoveRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpChangeProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/MD5Util.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ClientTrackServiceTest.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/code/StartingSpringApplicationRunListener.java
  core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/core/ServerReloaderRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  core/src/main/java/com/alibaba/nacos/core/utils/Loggers.java
  core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java
  core/src/main/resources/META-INF/logback/nacos.xml
  distribution/conf/nacos-logback.xml
  istio/src/main/resources/gateway.proto
  istio/src/main/resources/status.proto
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HttpHealthCheckProcessor.java
  sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java
  test/src/test/resources/logback-test.xml
Labels: kind/feature

#4211 [ISSUE #4199] Replace the http client implementation used by DistroFilter
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
Labels: kind/bug

#4207 [ISSUE #3102] remove lang/lang3 dependency from api/common/client.
  api/pom.xml
Labels: dependencies

#4205 Fix issue 4187
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
  core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java
Labels: area/Nacos Core, kind/bug

#4188 [ISSUE #4090] Configuration file changes do not take effect
  core/src/main/java/com/alibaba/nacos/core/code/StartingSpringApplicationRunListener.java
  sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
Labels: kind/enhancement

#4237 [ISSUE #4236] Add RequestContent and set attribute Overwrite to true to resolve the Apache Header Already Present problem
  common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
Labels: kind/bug

#4245 Fix sql injection bug
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
Labels: kind/bug

#4260 Adapt update service metadata api.
  console/src/main/resources/application.properties
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
Labels: kind/feature

#4244 [ISSUE #4225] Replace http client in HttpHealthCheckProcessor
  common/src/main/java/com/alibaba/nacos/common/http/AbstractApacheHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
  naming/pom.xml
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/PersistentNotifier.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HttpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
  pom.xml
Labels: kind/refactor

#4276 Optimize Bean injection and fix unsafe Map removal issues
  common/pom.xml
  common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
  common/src/main/java/com/alibaba/nacos/common/utils/MapUtil.java
  common/src/test/java/com/alibaba/nacos/common/utils/MapUtilTest.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfiRemoveRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigClusterRpcClientProxy.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/result/ResultBuilder.java
  config/src/main/java/com/alibaba/nacos/config/server/result/code/ResultCodeEnum.java
  config/src/main/java/com/alibaba/nacos/config/server/result/core/IResultCode.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocol.java
Labels: kind/refactor

#4279 Support update instance metadata and sync by raft
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/feature

#4298 [ISSUE-#4293] Remove env operation code in ApplicationUtils
  sys/src/main/java/com/alibaba/nacos/sys/utils/ApplicationUtils.java
Labels: kind/refactor

#4299 [ISSUE #4275] replace com.alibaba.nacos.config.server.result.ResultBuilder to RestResultUtil
  common/src/main/java/com/alibaba/nacos/common/model/RestResultUtils.java
  common/src/main/java/com/alibaba/nacos/common/model/core/IResultCode.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/result/ResultBuilder.java
  config/src/main/java/com/alibaba/nacos/config/server/result/code/ResultCodeEnum.java
Labels: kind/refactor

#4287 [ISSUE-#4286] When auth open, use resource parser cache to parse resource
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
Labels: kind/enhancement

#4313 [ISSUE #4311] Fix Derby data source related SQL LIMIT exception
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
Labels: kind/bug

#4321 [ISSUE #4320] Fixing the Naming consistency module could not start in cluster mode
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/PersistentConsistencyServiceDelegateImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/StandalonePersistentServiceProcessor.java
Labels: kind/bug

#4259 [ISSUE-#4258] Fix wrong path when -Dspring.config.location not set
  sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
Labels: kind/refactor

#4339 Upgrade jraft to 1.3.5
  api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
  pom.xml
Labels: dependencies

#4343 [ISSUE-#4342] Fix nacos.core.protocol.raft.data.read_index_type isn't effect
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/RaftSysConstants.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/RaftOptionsBuilder.java
Labels: area/Nacos Core, kind/bug

#4334 [ISSUE-#4333]Add MapRowMapper to RowMapperManager
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
Labels: area/Config, kind/enhancement

#4354 Refactor auto cleaner to adapt clean metadata
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/AbstractNamingCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/NamingCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/metadata/MetadataEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ExpiredMetadataInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
Labels: kind/feature

#4326 [ISSUE-#4181] Normalize ContextPath value in client-side
  client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
  client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
  client/src/main/java/com/alibaba/nacos/client/utils/ContextPathUtil.java
  client/src/test/java/com/alibaba/nacos/client/utils/ContextPathUtilTest.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_CITCase.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigAPI_With_RootContextPath_CITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_With_RootContextPath_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java
  test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_With_RootContextPath_ITCase.java
Labels: area/Config, kind/enhancement

#4362 The button '新建命名空间' misses marginRight on the page '命名空间'
  console-ui/src/pages/NameSpace/NameSpace.js
Labels: area/Nacos console, kind/user experience

#4363 Add the function of automatically clearing empty services
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ExpiredMetadataInfo.java
Labels: kind/feature

#4367 Add metadata dump and load jraft snapshot
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/AbstractHealthChecker.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Http.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Mysql.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/impl/Tcp.java
  api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/TestChecker.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/AbstractSnapshotOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/AbstractMetadataSnapshotOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ClusterMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataSnapshotOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadata.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataSnapshotOperation.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java
  naming/src/main/java/com/alibaba/nacos/naming/selector/Selector.java
  pom.xml
  sys/src/main/java/com/alibaba/nacos/sys/utils/DiskUtils.java
Labels: kind/feature

#4347 [ISSUE-#4346] Fix import code
  core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigExportAndImportAPI_CITCase.java
  test/src/test/java/com/alibaba/nacos/test/naming/RegisterInstance_ITCase.java
Labels: area/Test, kind/code quality
