Repository alibaba/nacos, pull requests merged in 2020-08, with the labels that each got.

#3507 [ISSUE #3439] Increment console config page size
  console/src/main/resources/static/console-fe/src/constants.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/src/main/resources/static/console-fe/src/pages/ServiceManagement/ServiceList/ServiceList.js
Labels: area/Nacos console, kind/enhancement

#3505 [ISSUE #3397]Fix shell syntax error when running in ubuntu
  distribution/bin/shutdown.sh
  distribution/bin/startup.sh
Labels: kind/bug

#3521 Add gprc support-> server push ack
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeNotifyResponse.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/PushCallBack.java
  client/src/main/resources/nacos-log4j2.xml
  client/src/main/resources/nacos-logback.xml
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeNotifier.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectCoordinator.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcAckSynchronizer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestHandlerReactor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcStreamRequestHanderImpl.java
Labels: kind/feature

#3516 [#3509] Fix address server mode cannot be obtained application.properties
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
  distribution/conf/application.properties
  distribution/conf/application.properties.example
Labels: kind/enhancement

#3432 [#3368]Cancel empty Long polling thread to improve performance.
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/test/java/com/alibaba/nacos/client/config/listener/impl/ClientWorkerTest.java
Labels: kind/enhancement

#3523 [ISSUE #3192] replace nacos-config module http client
  common/src/main/java/com/alibaba/nacos/common/http/client/NacosAsyncRestTemplate.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ClientIpWhiteList.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/HttpClientManager.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/JSONUtils.java
  test/src/test/java/com/alibaba/nacos/test/common/NacosAsyncRestTemplate_ITCase.java
  test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_ITCase.java
Labels: kind/refactor

#3522 When binding roles, the user list is changed to the drop-down selection mode （在绑定角色的时候用户列表改成下拉选中的模式) #3518
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/RolePersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/UserPersistService.java
  console/src/main/java/com/alibaba/nacos/console/controller/RoleController.java
  console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java
  console/src/main/resources/static/console-fe/src/pages/AuthorityControl/PermissionsManagement/NewPermissions.js
  console/src/main/resources/static/console-fe/src/pages/AuthorityControl/RolesManagement/NewRole.js
  console/src/main/resources/static/console-fe/src/reducers/authority.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/enhancement, kind/user experience

#3535 [ISSUE #3192] replace nacos-core module http client
  common/src/main/java/com/alibaba/nacos/common/http/BaseHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientManager.java
  common/src/main/java/com/alibaba/nacos/common/http/NAsyncHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NSyncHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NacosAsyncHttpClient.java
  common/src/main/java/com/alibaba/nacos/common/http/NacosSyncHttpClient.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java
  test/src/test/java/com/alibaba/nacos/test/core/BaseClusterTest.java
Labels: kind/refactor

#3487 [ISSUE #3486] Fix com.alibaba.nacos.core.code.ControllerMethodsCache will mismatch sometimes
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/auth/RequestMappingInfo.java
  core/src/main/java/com/alibaba/nacos/core/auth/condition/ParamRequestCondition.java
  core/src/main/java/com/alibaba/nacos/core/auth/condition/PathRequestCondition.java
  core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
  core/src/main/java/com/alibaba/nacos/core/utils/Constants.java
  naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java
  test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCacheTest.java
Labels: kind/bug, kind/enhancement

#3543 Fix #3269 When nacos.core.auth.enabled = true, user information is saved to the request in login
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
Labels: area/Nacos console, kind/enhancement

#3547 [ISSUE #3536] upgrade Jjwt to 0.11.2
  console/src/main/java/com/alibaba/nacos/console/utils/JwtTokenUtils.java
  pom.xml
Labels: kind/enhancement

#3551 [ISSUE #3550]. fix instance cache file can't create in server side
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
Labels: kind/bug

#3552 ISSUE #2792historyDetail page and historyRollback page add field 'srU…
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/HistoryDetail/HistoryDetail.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/enhancement

#3553 ISSUE #3530 add button for user role page
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/AuthorityControl/PermissionsManagement/PermissionsManagement.js
  console/src/main/resources/static/console-fe/src/pages/AuthorityControl/RolesManagement/RolesManagement.js
  console/src/main/resources/static/console-fe/src/pages/AuthorityControl/UserManagement/UserManagement.js
  console/src/main/resources/static/console-fe/src/pages/NameSpace/NameSpace.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/user experience

#3570 On click nacos logo jump to index page
  console/src/main/resources/static/console-fe/src/layouts/Header.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/user experience

#3555 [ISSUE #1654] Fix content hightlight does not work in config detail page
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/enhancement, kind/user experience

#3563 [ISSUE #3515] upgrade spring-boot-dependencies version to 2.1.16.RELE…
  pom.xml
Labels: kind/proposal

#3590 [ISSUE #3566] create a nacos-auth module
  auth/pom.xml
  core/pom.xml
  pom.xml
Labels: kind/refactor

#3596 [ISSUE #3595] delete the unnecessary code if com.alibaba.nacos.core.utils.InetUtils static code
  core/src/main/java/com/alibaba/nacos/core/utils/InetUtils.java
Labels: kind/code quality

#3603 [ISSUE #3592] Fix incorrect prompt when accessing the restricted namespace
  console/src/main/resources/static/console-fe/src/locales/en-US.js
  console/src/main/resources/static/console-fe/src/locales/zh-CN.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/bug

#3624 [ISSUE #3622] Move jwt dependency from console,core to auth.
  auth/pom.xml
  auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
  console/pom.xml
  core/pom.xml
Labels: kind/code quality, kind/refactor

#3630 listen context query support on console ; basic api for lader balance ;server side push retry submit
  api/pom.xml
  api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectResetRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectionSetupRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/ServerPushResponse.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/test/java/com/alibaba/nacos/client/ConfigTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/Connection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ConnectionEventListener.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  common/src/test/java/com/alibaba/nacos/common/remote/RSocketRpcClientTest.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigConnectionEventListener.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/GroupKeyContext.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerLoaderController.java
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMetaInfo.java
  core/src/main/java/com/alibaba/nacos/core/remote/DefaultPushFuture.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcPushService.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  test/src/test/java/com/alibaba/nacos/test/core/RsocketClientTest.java
  tree.txt
Labels: kind/feature

#3637 [ISSUE #3628] set naming client updateTask interval more flexible
  client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
Labels: kind/enhancement

#3662 Fix issue 3661
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
Labels: kind/bug

#3672 [ISSUE #3671] move some tools class into common package
  client/src/main/java/com/alibaba/nacos/client/config/impl/SpasAdapter.java
  client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/SignUtil.java
  common/src/main/java/com/alibaba/nacos/common/codec/Base64.java
  common/src/main/java/com/alibaba/nacos/common/utils/IpUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/IPUtil.java
Labels: kind/refactor

#3668 for #3621
  client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
Labels: kind/enhancement

#3703 [ISSUE #3651] Try to fix nacos server CLOSE_WAIT
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
Labels: kind/enhancement

#3686 [ISSUE #3676] Fix revert chunk isn't work in Content Comparison page
  console/src/main/resources/static/console-fe/src/components/DiffEditorDialog/DiffEditorDialog.js
  console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/bug
