Repository alibaba/nacos, pull requests merged in 2020-12, with the labels that each got.

#4376 Naming global config unified use EnvUtils tool
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
Labels: kind/refactor

#4381 Fix some bugs for naming module
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java
  client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/handler/SubscribeServiceRequestHandler.java
Labels: kind/bug

#4402 [ISSUE-#4401] When deleteFile, just check the file is exists.
  sys/src/main/java/com/alibaba/nacos/sys/utils/DiskUtils.java
Labels: kind/refactor

#4394 [ISSUE-#4393] Use PeerId.getEndpoint() to replace new Object
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
Labels: kind/refactor

#4384 Fix an order-dependent flaky test
  api/src/test/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckerFactoryTest.java
Labels: area/Test

#4413 [ISSUE #4412]: Update comment error
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
Labels: kind/code quality

#4419 [ISSUE #4412]: Update comment error
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
Labels: kind/code quality

#4461 Refactor PushService to separate subscriber logic.
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ApiController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/push/DataSource.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceAggregationImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushClient.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
  naming/src/test/java/com/alibaba/nacos/naming/core/PushServiceTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceV1ImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/PushClientTest.java
Labels: kind/refactor

#4451 [ISSUE-#4450] Fix memberAddressInfos not right problem when memberChange
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
Labels: kind/bug

#4445 [ISSUE #4344] cacheMap property optimization
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
Labels: area/Client, kind/refactor

#4469 [ISSUE #4415] fix NOW_WATCH_JOB_CNT record WatchDirJob count
  sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java
Labels: kind/bug

#4473 rsocket parse bugfix; auth bugfix;some checkstyle and basic spell fix.
  api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketRpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigRemoveRequestHandler.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
  core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
  test/src/test/java/com/alibaba/nacos/test/config/ConfigTest.java
Labels: kind/bug

#4486 [ISSUE #4477] fix service/list fromIndex > toIndex
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java
Labels: kind/bug

#4468 [ISSUE-#4467] Fix snowflake id problem
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
Labels: kind/bug

#4492 Refactor udp push service
  naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
  naming/src/main/java/com/alibaba/nacos/naming/push/AckEntry.java
  naming/src/main/java/com/alibaba/nacos/naming/push/AckPacket.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecutor.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecutorDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecutorRpcImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushExecutorUdpImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceListRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
Labels: kind/refactor

#4488 refactor(console): add fuzzy tips
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
Labels: area/Nacos console, kind/user experience

#4502 [ISSUE #4489] Fix can't query non-default-group problem for catalog API
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
Labels: kind/bug

#4371 [ISSUE #4364] Fix Cluster member state isn't updated to 'DOWN' after the node becomes down
  common/src/main/java/com/alibaba/nacos/common/utils/ExceptionUtil.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/FileConfigMemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/StandaloneMemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
  core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilsTest.java
  naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java
  test/src/test/java/com/alibaba/nacos/test/core/cluster/ServerMemberManager_ITCase.java
Labels: area/Nacos Core, kind/bug

#4527 [ISSUE #4424] Fixed issue where null values could not be converted to base parameters
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
Labels: kind/bug

#4517 [ISSUE #4463] fix derbyOps interface security problem
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
Labels: area/Config, kind/enhancement

#4514 [ISSUE-#4513] Check instance illegal heart beat param before register
  api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
Labels: kind/enhancement

#4533 Add callback, simple retry and metric for naming push
  api/src/main/java/com/alibaba/nacos/api/naming/NamingResponseCode.java
  client/src/main/java/com/alibaba/nacos/client/naming/event/InstancesChangeNotifier.java
  common/src/main/java/com/alibaba/nacos/common/notify/DefaultPublisher.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/Service.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceAggregationImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/NoRequiredRetryException.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutor.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/udp/AckEntry.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/udp/AckPacket.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
  naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/monitor/MetricsMonitorTest.java
Labels: kind/feature

#4572 [ISSUE-#4567] Refactor nacos-client Load Logging Configuration code.
  client/src/main/java/com/alibaba/nacos/client/logging/NacosLogging.java
  client/src/main/java/com/alibaba/nacos/client/utils/LogUtils.java
Labels: kind/refactor

#4548 encode bugfix
  api/src/main/java/com/alibaba/nacos/api/cmdb/spi/CmdbService.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigBatchListenRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/cluster/ConfigChangeClusterSyncRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigChangeBatchListenResponse.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigPublishResponse.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigQueryResponse.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/response/ConfigRemoveResponse.java
  api/src/main/java/com/alibaba/nacos/api/exception/NacosException.java
  api/src/main/java/com/alibaba/nacos/api/remote/DefaultRequestFuture.java
  api/src/main/java/com/alibaba/nacos/api/remote/RequestCallBack.java
  api/src/main/java/com/alibaba/nacos/api/remote/RequestFuture.java
  api/src/main/java/com/alibaba/nacos/api/remote/Requester.java
  api/src/main/java/com/alibaba/nacos/api/remote/RpcScheduledExecutor.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/Request.java
  api/src/main/java/com/alibaba/nacos/api/remote/response/Response.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
  client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java
  client/src/main/resources/nacos-log4j2.xml
  client/src/main/resources/nacos-logback.xml
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ServerListFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/rsocket/RsocketConnection.java
  common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  core/src/main/java/com/alibaba/nacos/core/remote/BaseRpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListener.java
  core/src/main/java/com/alibaba/nacos/core/remote/ClientConnectionEventListenerRegistry.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/RequestHandlerRegistry.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketConnection.java
  core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java
Labels: kind/bug

#4578 Refactor SubscribeManager with NamingSubscriberServiceAggregationImpl
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/SubscribeManager.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceAggregationImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceLocalImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/UdpPushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v1/ClientInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v1/DataSource.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v1/NamingSubscriberServiceV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v1/PushClient.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v1/ServiceChangeEvent.java
  naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/NamingSubscriberServiceAggregationImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v1/ClientInfoTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v1/NamingSubscriberServiceV1ImplTest.java
Labels: kind/refactor

#4584 [ISSUE #4583] Fix DOMAIN mode retry logic
  api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
Labels: kind/bug

#4579 [ISSUE #4570]fix cluster mode query config type is null
  config/src/main/java/com/alibaba/nacos/config/server/model/ConfigAllInfo.java
Labels: kind/bug

#4536 [ISSUE #3406] fix change self's password fail
  console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
  test/src/test/java/com/alibaba/nacos/test/core/auth/User_ITCase.java
Labels: area/Nacos Core, kind/bug

#4590 Fix the configuration file loading issue #4556 #4541
  core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java
  distribution/bin/startup.cmd
  distribution/bin/startup.sh
  sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
  sys/src/main/java/com/alibaba/nacos/sys/env/NacosAutoRefreshPropertySourceLoader.java
  sys/src/main/resources/META-INF/spring.factories
  sys/src/test/java/com/alibaba/nacos/sys/env/NacosAutoRefreshPropertySourceLoaderTest.java
Labels: kind/bug

#4586 [ISSUE#4355] Do not retry distro sync again if member has removed.
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroHttpRegistry.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
Labels: area/Nacos Core, kind/enhancement

#4595 Execute Distro transport asynchronously.
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroTransportAgent.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/entity/DistroKey.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/delay/DistroDelayTaskProcessor.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/AbstractDistroExecuteTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroSyncChangeTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/DistroSyncDeleteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroHttpAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
Labels: kind/enhancement

#4603 refactor: 持久化实例
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/BaseClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/IpPortBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/NoConnectionClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
Labels: kind/feature

#4608 Support persistent service and instance register/deregister
  common/src/main/java/com/alibaba/nacos/common/utils/ThreadUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/BaseClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
Labels: kind/feature

#4606 [ISSUE-#4594,#4596] Fix IO close problem
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java
  client/src/main/java/com/alibaba/nacos/client/config/utils/ConcurrentDiskUtil.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java
  common/src/main/java/com/alibaba/nacos/common/http/client/request/JdkHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/client/response/HttpClientResponse.java
  common/src/main/java/com/alibaba/nacos/common/utils/IoUtils.java
  common/src/main/java/com/alibaba/nacos/common/utils/ResourceUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
  test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_Interceptors_ITCase.java
Labels: kind/code quality, kind/refactor

#4607 优化 FileTypeEnum 取值逻辑, 避免使用异常当作逻辑分支
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/enums/FileTypeEnum.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  test/src/test/java/com/alibaba/nacos/test/common/FileTypeEnum_ITCase.java
Labels: kind/refactor
