Repository alibaba/nacos, pull requests merged in 2021-05, with the labels that each got.

#5614 add unit test for ServiceMetadataProcessor
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessorTest.java
Labels: area/Test

#5613 [ISSUE #5522] add unit test for ServiceMetadataSnapshotOperation
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataSnapshotOperationTest.java
Labels: area/Test

#5610 [ISSUE #5522] add unit test for NamingMetadataOperateService
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateServiceTest.java
Labels: area/Test

#5608 [ISSUE #5522] add unit test for MetadataOperation
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/metadata/MetadataOperationTest.java
Labels: area/Test

#5548 Optimize ConfigRequest and ConfigResponse code, extract common constants
  client/src/main/java/com/alibaba/nacos/client/config/common/ConfigConstants.java
  client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequest.java
  client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigResponse.java
Labels: kind/code quality

#5563 Add unit tests for package com.alibaba.nacos.naming.core.v2.index
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorageTest.java
Labels: area/Test

#5575 [ISSUE #5574] Remove downgraded member version info.
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
Labels: kind/bug, version/2.x

#5582 [#5581] The class DataStore lacks a lot of Unit Tests.
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DataStoreTest.java
Labels: area/Test

#5602 [#5595] Package com.alibaba.nacos.core.distributed.distro.entity lacks a lot of Unit tests
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/entity/DistroDataTest.java
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/entity/DistroKeyTest.java
Labels: area/Test

#5604 [#5599] The class com.alibaba.nacos.core.distributed.distro.DistroConfig lacks Unit Test.
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java
Labels: area/Test

#5606 [#5601] The package com.alibaba.nacos.core.distributed.distro.component lacks Unit Tests.
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/component/DistroComponentHolderTest.java
Labels: area/Test

#5578 [#5577] The AddressServerMemberLookupTest class lacks corresponding Unit Tests.
  core/src/test/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookupTest.java
Labels: area/Test

#5619 [ISSUE #5617] The Query Parameter Lose
  console-ui/src/pages/ConfigurationManagement/HistoryDetail/HistoryDetail.js
Labels: area/Nacos console, kind/bug

#5637 [ISSUE #5635] button to add margin-right
  console-ui/src/pages/AuthorityControl/PermissionsManagement/PermissionsManagement.js
  console-ui/src/pages/AuthorityControl/RolesManagement/RolesManagement.js
  console-ui/src/pages/AuthorityControl/UserManagement/UserManagement.js
Labels: area/Nacos console, kind/enhancement

#5561 Deal with the concurrency of ClientLongPolling and DataChangeTask about allSubs
  config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
Labels: pending

#5679 [ISSUE #5155] Add unit tests for package com.alibaba.nacos.client.naming.remote in nacos 2.0
  client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingMaintainServiceTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
Labels: area/Test

#5686 Add monitor for Distro
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecord.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecordsHolder.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/execute/AbstractDistroExecuteTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyExecuteTask.java
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecordsHolderTest.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
Labels: kind/feature

#5587 Change the invalid compare in NotifySingleService
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java
Labels: status/need discuss

#5620 [ISSUE #5538] fix test case fail
  common/src/main/java/com/alibaba/nacos/common/utils/IPUtil.java
  common/src/test/java/com/alibaba/nacos/common/utils/IPUtilTest.java
  test/src/test/java/com/alibaba/nacos/test/core/JacksonUtils.java
Labels: area/Test

#5706 [ISSUE #5692] Make service removal sensed by double write.
  naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteAction.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListener.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV1Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV2Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/AsyncServicesCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV2Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV1Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV2Task.java
Labels: kind/bug, version/2.x

#5714 [ISSUE #5663] add unit test for ServiceChangeEvent
  naming/src/test/java/com/alibaba/nacos/naming/push/v1/ServiceChangeEventTest.java
Labels: area/Test

#5716 [ISSUE #5663] add unit test for SpiImplPushExecutorHolder
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/executor/SpiImplPushExecutorHolderTest.java
Labels: area/Test

#5717 Extract constants in HealthController
  naming/src/main/java/com/alibaba/nacos/naming/constants/RequestConstant.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
Labels: kind/code quality

#5719 [ISSUE #5718] Add some APIs for upgrade ops.
  naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java
Labels: kind/feature

#5725 Extract constants in JacksonSerializer
  naming/src/main/java/com/alibaba/nacos/naming/cluster/transport/JacksonSerializer.java
Labels: kind/code quality

#5729 [ISSUE #5727 auth] improve the code quality of nacos-config
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/PermissionPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/RolePersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/UserPersistService.java
Labels: kind/code quality

#5730 [ISSUE #5727 aspect] improve the code quality of nacos-config
  config/src/main/java/com/alibaba/nacos/config/server/aspect/CapacityManagementAspect.java
Labels: kind/code quality

#5731 [ISSUE #5727 controller] improve the code quality of nacos-config
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
Labels: kind/code quality

#5732 [ISSUE #5727 remote] improve the code quality of nacos-config
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishGroupKeyParser.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishGroupParser.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryGroupKeyParser.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryGroupParser.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/InternalConfigChangeNotifier.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
Labels: kind/code quality

#5751 [Refactor]Remove duplicate client expire check
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
Labels: kind/refactor

#5752 [ISSUE #5727 service-2] improve the code quality of nacos-config
  config/src/main/java/com/alibaba/nacos/config/server/service/ClientIpWhiteList.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/StandaloneDatabaseOperateImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
Labels: kind/code quality

#5758 [ISSUE #5747][v2] support of specifying NAMING_CACHE_REGISTRY_DIR property
  api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
Labels: area/Client, kind/enhancement

#5744 [ISSUE #5727 service-1] improve the code quality of nacos-config
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/LocalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpChangeProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeDatumService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/merge/MergeTaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
Labels: kind/code quality

#5773 [ISSUE #3046] Enhancement for constant variables
  config/src/main/java/com/alibaba/nacos/config/server/constant/PropertiesConstant.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
Labels: kind/refactor

#5781 [ISSUE #5774] improve the code quality of nacos-naming
  naming/src/main/java/com/alibaba/nacos/naming/cluster/remote/request/AbstractClusterRequest.java
Labels: kind/refactor

#5814 [ISSUE-#5713] fix the query param lost when use enter press to search in Nacos 1.x.
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/enhancement

#5819 [FOR #5802 notify/http] improve the code quality of nacos-common.
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/http/client/request/JdkHttpClientRequest.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
Labels: kind/code quality, kind/refactor

#5820 [FOR #5802 remote/spi] improve the code quality of nacos-common.
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcUtils.java
  common/src/main/java/com/alibaba/nacos/common/spi/NacosServiceLoader.java
Labels: kind/code quality, kind/refactor

#5832 [ISSUE#5831] Remove the sets in connection event lister
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListener.java
Labels: kind/bug

#5780 [ISSUE #5779] Use the correct serviceManager version to get the service list
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java
Labels: area/Istio

#5847 [FOR #5843 filter/security] improve the code quality of nacos-console.
  console/src/main/java/com/alibaba/nacos/console/filter/JwtAuthenticationTokenFilter.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/LdapAuthenticationProvider.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
  console/src/main/resources/META-INF/nacos-default.properties
Labels: kind/refactor

#5873 [ISSUE #5872] Downgrade checker only focus on changing members.
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MembersChangeEvent.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
Labels: kind/bug

#5852 [ISSUE #5765] fix localhost not match ip
  address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java
  address/src/main/java/com/alibaba/nacos/address/controller/AddressServerClusterController.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/config/utils/ParamUtils.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  common/src/main/java/com/alibaba/nacos/common/tls/SelfHostnameVerifier.java
  common/src/main/java/com/alibaba/nacos/common/utils/InternetAddressUtil.java
  common/src/test/java/com/alibaba/nacos/common/utils/InternetAddressUtilTest.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/SystemConfig.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/NetUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/ServerStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/ServiceStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java
  sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
  sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
Labels: kind/bug
