Repository alibaba/nacos, pull requests merged in 2021-11, with the labels that each got.

#7144 [ISSUE #5092] add unit tests for CommunicationController in nacos-config
  config/src/test/java/com/alibaba/nacos/config/server/controller/CommunicationControllerTest.java
Labels: area/Test

#7140 [ISSUE #5092] add unit tests for CapacityController in nacos-config
  config/src/test/java/com/alibaba/nacos/config/server/controller/CapacityControllerTest.java
Labels: area/Test

#7163 Remove useless grpc code.
  api/src/main/java/com/alibaba/nacos/api/grpc/auto/RequestStreamGrpc.java
  core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java
Labels: kind/refactor

#7174 Refactor Server ability init login with SPI.
  api/src/main/java/com/alibaba/nacos/api/ability/ClientAbilities.java
  api/src/main/java/com/alibaba/nacos/api/ability/ServerAbilities.java
  api/src/main/java/com/alibaba/nacos/api/ability/initializer/AbilityInitializer.java
  api/src/main/java/com/alibaba/nacos/api/config/ability/ClientConfigAbility.java
  api/src/main/java/com/alibaba/nacos/api/config/ability/ServerConfigAbility.java
  api/src/main/java/com/alibaba/nacos/api/naming/ability/ClientNamingAbility.java
  api/src/main/java/com/alibaba/nacos/api/naming/ability/ServerNamingAbility.java
  api/src/main/java/com/alibaba/nacos/api/remote/ability/ClientRemoteAbility.java
  api/src/main/java/com/alibaba/nacos/api/remote/ability/ServerRemoteAbility.java
  api/src/test/java/com/alibaba/nacos/api/naming/ability/ServerNamingAbilityTest.java
  core/src/main/java/com/alibaba/nacos/core/ability/RemoteAbilityInitializer.java
  core/src/main/java/com/alibaba/nacos/core/ability/ServerAbilityInitializer.java
  core/src/main/java/com/alibaba/nacos/core/ability/ServerAbilityInitializerHolder.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/resources/META-INF/services/com.alibaba.nacos.core.ability.ServerAbilityInitializer
  core/src/test/java/com/alibaba/nacos/core/ability/RemoteAbilityInitializerTest.java
  core/src/test/java/com/alibaba/nacos/core/ability/ServerAbilityInitializerHolderTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/ServerLoaderControllerTest.java
  naming/src/main/java/com/alibaba/nacos/naming/ability/NamingAbilityInitializer.java
  naming/src/main/resources/META-INF/services/com.alibaba.nacos.core.ability.ServerAbilityInitializer
  naming/src/test/java/com/alibaba/nacos/naming/ability/NamingAbilityInitializerTest.java
Labels: kind/feature, kind/refactor

#7186 [ISSUE #5092] add unit tests for ConfigController in nacos-config
  config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigControllerTest.java
Labels: area/Test

#7211 [ISSUE#7210] Add service rest api for v2.
  console/src/main/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ClusterInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceDetailInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceNameView.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerV2Test.java
Labels: kind/feature

#7236 [ISSUE #7225] Ignore the WebServerInitializedEvent if the name space of the spring context is management
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
Labels: kind/bug

#7239 [ISSUE#6846] Make one service keep one kind of instance (ephemeral or persistent).
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImplTest.java
  test/naming-test/src/test/java/com/alibaba/nacos/test/naming/CPInstancesAPI_ITCase.java
Labels: kind/enhancement

#7262 Add ephmeral attribute in v2 service query api.
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceDetailInfo.java
Labels: kind/feature

#7263 [ISSUE #5092] add unit test for DiskUtils in nacos-config
  config/src/test/java/com/alibaba/nacos/config/server/utils/DiskUtilsTest.java
Labels: area/Test
