Repository alibaba/nacos, pull requests merged in 2021-03, with the labels that each got.

#4948 [ISSUE #4925] correct the member's state when the cluster information…
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
Labels: kind/bug

#4977 compatible with the reflection logic of Dubbo 2.7.X
  client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
Labels: area/Client

#4993 For #4987, Fix throw exception when build ClientInfo with empty user-agent.
  naming/src/main/java/com/alibaba/nacos/naming/push/v1/ClientInfo.java
Labels: kind/bug, version/2.x

#4994 For #4989, fix throws NPE when some metadata value is null.
  naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java
Labels: kind/bug, version/2.x

#4998 Single push to client when client subscribe service.
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2ImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngineTest.java
Labels: kind/feature

#5002 [ISSUE #4996]core add log change
  core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java
  core/src/main/java/com/alibaba/nacos/core/utils/Loggers.java
Labels: kind/feature

#5010 fix TemplateUtils usage
  client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
  client/src/main/java/com/alibaba/nacos/client/utils/TemplateUtils.java
Labels: kind/enhancement

#5017 Refactor and enhance for client distro protocol
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroProtocol.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroDataProcessor.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/component/DistroDataStorage.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyExecuteTask.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/task/verify/DistroVerifyTimedTask.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientVerifyInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/DistroController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandler.java
Labels: kind/refactor, version/2.x

#5022 [ISSUE-#4306] StringJoiner should consider '@@'.
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
Labels: kind/bug

#5055 [ISSUE #5054] Support naming instance list with healthy protection using service.protectionThreshold.
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/enhancement, version/2.x

#5045 [ISSUE #5030] add ut for package com.alibaba.nacos.client.config.common
  client/src/test/java/com/alibaba/nacos/client/config/common/GroupKeyTest.java
Labels: area/Test

#5068 shade client and using remote ip from header
  api/src/main/java/com/alibaba/nacos/api/remote/PayloadRegistry.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectionSetupRequest.java
  client/pom.xml
  client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManager.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  core/pom.xml
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  pom.xml
Labels: kind/enhancement

#5029 [ISSUE #5026]fix MetricsHttpAgent metrics twice
  client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java
Labels: kind/enhancement

#5069 [ISSUE #5067] Listing instances and marked as healthy state when heal…
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/bug, version/2.x

#5046 [ISSUE #5032] add ut for package com.alibaba.nacos.client.config.filter
  client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigContextTest.java
  client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigFilterChainManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigRequestTest.java
  client/src/test/java/com/alibaba/nacos/client/config/filter/impl/ConfigResponseTest.java
Labels: area/Test

#5049 [ISSUE #5036]add ut for com.alibaba.nacos.client.config.listener
  client/src/test/java/com/alibaba/nacos/client/config/impl/ConfigChangeHandlerTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/PropertiesChangeParserTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/YmlChangeParserTest.java
  client/src/test/java/com/alibaba/nacos/client/config/listener/impl/AbstractConfigChangeListenerTest.java
  client/src/test/java/com/alibaba/nacos/client/config/listener/impl/PropertiesListenerTest.java
Labels: area/Test

#5050 [ISSUE #5037]add ut for package com.alibaba.nacos.client.config.utils
  client/src/test/java/com/alibaba/nacos/client/config/utils/ConcurrentDiskUtilTest.java
  client/src/test/java/com/alibaba/nacos/client/config/utils/ContentUtilsTest.java
  client/src/test/java/com/alibaba/nacos/client/config/utils/JvmUtilTest.java
  client/src/test/java/com/alibaba/nacos/client/config/utils/ParamUtilsTest.java
  client/src/test/java/com/alibaba/nacos/client/config/utils/SnapShotSwitchTest.java
Labels: area/Test

#5079 listener bugfix
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
Labels: kind/bug

#5081 [ISSUE #5080] Fix health checker pre-start logic.
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/MysqlHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
Labels: kind/bug, version/2.x

#5085 [ISSUE #5070] Fix catalog instance listing, make selectInstancesWithHealthyProtection isolated.
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/bug, version/2.x

#5091 Use hook to monitor and report push result.
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/NacosMonitorPushResultHook.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResult.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResultHook.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/PushResultHookHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.push.v2.hook.PushResultHook
Labels: kind/refactor

#5088 [ISSUE #5087] Enabled healthy protection threshold when pushing insta…
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngine.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2ImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushDelayTaskExecuteEngineTest.java
Labels: kind/enhancement

#5104 [ISSUE #5103] add ut for package com.alibaba.nacos.client.config.impl
  client/src/test/java/com/alibaba/nacos/client/config/impl/CacheDataTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/LimiterTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/SpasAdapterTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/YmlChangeParserTest.java
Labels: area/Test

#5102 [ISSUE #4452]add config compare feat
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigCompared.js
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
Labels: kind/feature

#5048 [ISSUE #5034] add ut for package com.alibaba.nacos.client.config.http
  client/src/test/java/com/alibaba/nacos/client/config/http/MetricsHttpAgentTest.java
  client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
Labels: area/Test

#5122 [ISSUE #5114]Fix `ConcurrentHashSet` compatibility problems
  common/src/main/java/com/alibaba/nacos/common/utils/ConcurrentHashSet.java
Labels: kind/bug

#5128 [#4822,#4823,#4824,#4825,#4979] Fix dependency security problem.
  pom.xml
Labels: dependencies

#5131 [ISSUE#4829] Remove instance when distro and raft remove instances data.
  naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
Labels: kind/bug

#5129 [#4573,#4629] Jraft leader status check error.
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
Labels: kind/bug

#5156 [ISSUE #5149]Add unit tests for package c.a.nacos.client.naming.beat in nacos 2.0
  client/src/test/java/com/alibaba/nacos/client/BeatReactorTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/beat/BeatInfoTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/beat/BeatReactorTest.java
Labels: area/Test

#5165 [ISSUE #5150]Add unit tests for package c.a.nacos.client.naming.cache in nacos 2.0
  client/src/test/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtilTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/cache/DiskCacheTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolderTest.java
Labels: area/Test

#5185 [ISSUE #5137]service list add view subscriber feat
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/ServiceManagement/ServiceList/ServiceList.js
  console-ui/src/pages/ServiceManagement/SubscriberList/SubscriberList.js
Labels: area/Nacos console, kind/feature

#5188 [ISSUE #5178] Fix NPE when init server list failed.
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
Labels: area/Client, kind/bug

#5196 [ISSUE-#3779] GroupName can't be empty.
  api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
Labels: kind/code quality

#5201 [ISSUE-#5182] Remove ConfigController#removeRequestContext method.
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
Labels: area/Config, kind/bug

#5223 [ISSUE #4756]Fix config list sort and search problem
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
  console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js
Labels: area/Nacos console, kind/enhancement

#5228 [ISSUE #5204], Fix query error when pageNo is larger than service number.
  naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java
Labels: kind/bug, version/2.x

#5233 fix thread pool
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConnection.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
Labels: kind/bug

#5230 [ISSUE #5154]Add unit tests for package c.a.nacos.client.naming.utils in nacos 2.0
  client/src/test/java/com/alibaba/nacos/client/naming/utils/CollectionUtilsTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/utils/GenericPollerTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/utils/InitUtilsTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/utils/NamingHttpUtilTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/utils/PairTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/utils/SignUtilTest.java
Labels: area/Test

#5226 [WIP][ISSUE #5206] upgrade mockito from 2.3.24 to 3.8.0
  address/pom.xml
  pom.xml
Labels: area/Test, dependencies

#5193 [ISSUE #5151] add ut for package c.a.nacos.client.naming.core
  client/src/test/java/com/alibaba/nacos/client/naming/core/BalancerTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/ProtectModeTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/PushReceiverTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/ServerListManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateServiceTest.java
Labels: area/Test

#5237 Fix ThreadPool usage problem and add some monitor for distro
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcClusterServer.java
  core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java
  core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/NamingTpsMonitor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/TpsMonitorItem.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
Labels: kind/bug

#5186 [ISSUE #5175] fix publishConfig lost type
  client/src/main/java/com/alibaba/nacos/client/config/NacosConfigService.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
  client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
Labels: area/Client, area/Config

#5124 [ISSUE #4856]support mcp over xds
  NOTICE
  istio/pom.xml
  istio/src/main/java/com/alibaba/nacos/istio/mcp/CollectionTypes.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpOverXdsService.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpServer.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosMcpService.java
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java
  istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java
  istio/src/main/proto/gogoproto/gogo.proto
  istio/src/main/proto/google/protobuf/any.proto
  istio/src/main/proto/mcp/v1alpha1/mcp.proto
  istio/src/main/proto/mcp/v1alpha1/metadata.proto
  istio/src/main/proto/mcp/v1alpha1/resource.proto
  istio/src/main/proto/networking/v1alpha3/destination_rule.proto
  istio/src/main/proto/networking/v1alpha3/envoy_filter.proto
  istio/src/main/proto/networking/v1alpha3/gateway.proto
  istio/src/main/proto/networking/v1alpha3/service_entry.proto
  istio/src/main/proto/networking/v1alpha3/sidecar.proto
  istio/src/main/proto/networking/v1alpha3/virtual_service.proto
  istio/src/main/proto/networking/v1alpha3/workload_entry.proto
  istio/src/main/proto/networking/v1alpha3/workload_group.proto
  pom.xml
Labels: kind/feature
