Repository alibaba/nacos, pull requests merged in 2021-06, with the labels that each got.

#5907 [FOR 5904 env/file] improve the code quality of nacos-sys.
  sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
  sys/src/main/java/com/alibaba/nacos/sys/file/WatchFileCenter.java
Labels: kind/refactor

#5928 [ISSUE #5927] Init health check status when loading snapshot of persistent instances.
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
Labels: kind/bug

#5923 [FOR 5915 remote/utils] improve the code quality of nacos-api.
  api/src/main/java/com/alibaba/nacos/api/remote/RequestCallBack.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/ClientDetectionRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/ConnectResetRequest.java
  api/src/main/java/com/alibaba/nacos/api/remote/request/InternalRequest.java
  api/src/main/java/com/alibaba/nacos/api/utils/NetUtils.java
Labels: kind/refactor

#5922 [FOR 5915 naming] improve the code quality of nacos-api.
  api/src/main/java/com/alibaba/nacos/api/naming/NamingFactory.java
  api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainFactory.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/request/AbstractNamingRequest.java
  api/src/main/java/com/alibaba/nacos/api/naming/remote/request/NotifySubscriberRequest.java
Labels: kind/refactor

#5921 [FOR 5915 config] improve the code quality of nacos-api.
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/AbstractConfigRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ClientConfigMetricRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeNotifyRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java
Labels: kind/refactor

#5916 [ISSUS #5805]add unit test for c.a.n.client.identify
  client/src/test/java/com/alibaba/nacos/client/identify/CredentialServiceTest.java
  client/src/test/java/com/alibaba/nacos/client/identify/CredentialWatcherTest.java
  client/src/test/java/com/alibaba/nacos/client/identify/CredentialsTest.java
  client/src/test/java/com/alibaba/nacos/client/identify/StsConfigTest.java
Labels: area/Test

#5914 [ISSUE #5774] improve the code quality for naming core
  common/src/main/java/com/alibaba/nacos/common/task/AbstractDelayTask.java
  common/src/main/java/com/alibaba/nacos/common/task/AbstractExecuteTask.java
  naming/src/main/java/com/alibaba/nacos/naming/constants/FieldsConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Cluster.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV1Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/ServiceChangeV2Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/AsyncServicesCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DefaultInstanceUpgradeHelper.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteInstanceChangeToV1Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteInstanceChangeToV2Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV1Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteMetadataChangeToV2Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV1Task.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/DoubleWriteServiceRemovalToV2Task.java
Labels: kind/refactor

#5932 [ISSUE #5774] improve the code quality for naming healthcheck
  naming/src/main/java/com/alibaba/nacos/naming/constants/FieldsConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatProcessorV2.java
Labels: kind/refactor

#5925 [ISSUS #5804]add unit test for c.a.n.client.security
  client/src/test/java/com/alibaba/nacos/client/security/SecurityProxyTest.java
Labels: area/Test

#5972 [ISSUE#5921] Adapt some Naming API after upgrading to v2.x.
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
Labels: kind/bug

#5974 [ISSUE #5952] Feature make naming rpc client aware of server list change
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/event/ServerListChangedEvent.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxyTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
Labels: area/Client, kind/feature

#5889 Feat resource parser group
  config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
  config/src/test/java/com/alibaba/nacos/config/server/auth/ConfigResourceParserTest.java
  naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java
  naming/src/test/java/com/alibaba/nacos/naming/web/NamingResourceParserTest.java
Labels: kind/refactor

#6007 fix #5934
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
Labels: kind/bug

#6009 [FOR 5771 naming] improve the code quality of nacos-client.
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/beat/BeatReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ConcurrentDiskUtil.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/PushReceiver.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/Chooser.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/InitUtils.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/SignUtil.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/UtilAndComs.java
Labels: kind/refactor

#6017 fix #5934 for 2.x
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
Labels: kind/bug

#6014 [ISSUE#5835]Remove global params username.
  console-ui/src/globalLib.js
  console-ui/src/utils/request.js
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/bug

#6015 Add/Remove cache before call server.
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
Labels: area/Client, area/Naming, kind/enhancement

#6020 [ISSUE #6019] Support fetching server list from endpoint with namespace.
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
Labels: area/Client, kind/feature

#6022 [ISSUE #6019] Support fetching server list from endpoint with namespace.
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
Labels: area/Client, kind/feature

#6001 [ISSUE #5999] AddressServerMemberLookup.syncFromAddressUrl适配nacos endpoint
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
  core/src/test/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookupTest.java
Labels: kind/enhancement

#6031 [ISSUE#5982] Fix Unit test in nacos naming module
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingKvStorageTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ClusterTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceOperatorV1ImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2DelegateTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
Labels: area/Test

#5919 [code quality][nacos-address]improve the code of ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
Labels: kind/refactor

#6095 [ISSUE #6088] Simplify Assert
  client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/PropertiesChangeParserTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/YmlChangeParserTest.java
  common/src/test/java/com/alibaba/nacos/common/utils/InternetAddressUtilTest.java
  test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPollReturnChanges_CITCase.java
Labels: area/Test

#6101 [ISSUE#5990] Fix unit test problem for nacos-consistency.
  consistency/src/test/java/com/alibaba/nacos/consistency/ProtocolMetaDataTest.java
Labels: area/Test

#5995 [#5983] Fix unit tests in nacos-config
  config/src/test/java/com/alibaba/nacos/config/server/auth/MockAuthManager.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerUnitTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ConfigChangePublisherTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java
  config/src/test/resources/application.properties
Labels: area/Test

#6102 [ISSUE#5985] Fix unit test problem for nacos-core.
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/task/load/DistroLoadDataTaskTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/TpsMonitorManagerTest.java
  core/src/test/resources/application.properties
Labels: area/Test

#6106 [ISSUE#5976] Fail CI directly if UT can't pass.
  .github/workflows/ci.yml
  .github/workflows/maven.yml
  client/src/test/java/com/alibaba/nacos/client/config/impl/CacheDataTest.java
  core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java
  core/src/test/java/com/alibaba/nacos/core/remote/TpsMonitorManagerTest.java
  pom.xml
Labels: area/Test

#6118 [ISSUE#6116] Refactor ClientManager and make register client and schedule checkTask is atomic.
  core/src/test/java/com/alibaba/nacos/core/remote/TpsMonitorManagerTest.java
  naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientAttributes.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncData.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/PersistentIpPortClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClientTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessorTest.java
Labels: kind/bug

#6130 [ISSUE#6129] Add ServerConfigChangeEvent when config file changed.
  auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
  auth/src/test/java/com/alibaba/nacos/auth/common/AuthConfigsTest.java
  common/src/main/java/com/alibaba/nacos/common/event/ServerConfigChangeEvent.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
  core/src/main/java/com/alibaba/nacos/core/listener/StartingApplicationListener.java
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushConfig.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/PushConfigTest.java
Labels: kind/enhancement, kind/refactor

#6157 [FOR 5094 remote/control] add unit tests in nacos-core.
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/lookup/LookupFactoryTest.java
  core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/control/MonitorKeyMatcherTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/control/TpsMonitorManagerTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/control/TpsMonitorPointTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/control/TpsRecorderTest.java
Labels: area/Test

#6137 [ISSUE #5806]Add unit tests for package com.alibaba.nacos.client.logging in nacos
  client/src/test/java/com/alibaba/nacos/client/logging/AbstractNacosLoggingTest.java
  client/src/test/java/com/alibaba/nacos/client/logging/NacosLoggingTest.java
  client/src/test/java/com/alibaba/nacos/client/logging/log4j2/Log4J2NacosLoggingTest.java
  client/src/test/java/com/alibaba/nacos/client/logging/logback/LogbackNacosLoggingTest.java
Labels: area/Test

#6163 [ISSUE#6100] Enhance UI.
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/index.scss
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/index.scss
  console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console-ui/src/pages/ConfigurationManagement/NewConfig/index.scss
Labels: area/Nacos console, kind/enhancement

#6164 Fix: use revision to determine whether the service has changed
  istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java
Labels: area/Istio

#6165 [#6178] Unified configuration page style
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/index.scss
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
Labels: area/Nacos console

#6175 If the client already disconnect, ignore this request to avoid NPE.
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
Labels: kind/enhancement, kind/refactor

#6206 [ISSUE #6204] Get data from database if user or role info not found in cache
  console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/users/NacosUserDetailsServiceImpl.java
Labels: kind/enhancement

#6213 [ISSUE #6198] BUG nacos-common>utils>StringUtils.join method NullPointerException #6198
  common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/StringUtilsTest.java
Labels: kind/bug
