Repository alibaba/nacos, pull requests merged in 2021-09, with the labels that each got.

#6799 [ISSUE #6793] synchronize the betaIps in header and form data.
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console/src/main/resources/static/js/main.js
Labels: kind/enhancement, area/Nacos console

#6878 [ISSUE#5695] Summer2021 Cache encryptedDataKey
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/model/CacheItem.java
  config/src/main/java/com/alibaba/nacos/config/server/model/event/ConfigDumpEvent.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpConfigHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllBetaProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllTagProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpChangeProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/sql/EmbeddedStorageContextUtils.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ClientTrackServiceTest.java
Labels: kind/feature, Summer2021

#6879 [ISSUE#5695] Summer2021 Inheritance AbstractConfigFilter
  client/src/main/java/com/alibaba/nacos/client/config/AesCrypto.java
  client/src/main/java/com/alibaba/nacos/client/config/filter/impl/ConfigCryptoFilter.java
Labels: kind/feature, Summer2021

#6883 [ISSUE#5696] Add auth client: plugin and implement
  client/src/main/java/com/alibaba/nacos/client/auth/AbstractClientAuthService.java
  client/src/main/java/com/alibaba/nacos/client/auth/ClientAuthPluginManager.java
  client/src/main/java/com/alibaba/nacos/client/auth/ClientAuthService.java
  client/src/main/java/com/alibaba/nacos/client/auth/LoginAuthConstant.java
  client/src/main/java/com/alibaba/nacos/client/auth/LoginIdentityContext.java
  client/src/main/java/com/alibaba/nacos/client/auth/NacosClientAuthServiceImpl.java
  client/src/main/java/com/alibaba/nacos/client/auth/process/HttpLoginProcessor.java
  client/src/main/java/com/alibaba/nacos/client/auth/process/LoginProcessor.java
  client/src/main/resources/META-INF/services/com.alibaba.nacos.client.auth.AbstractClientAuthService
  client/src/test/java/com/alibaba/nacos/client/auth/ClientAuthPluginManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/auth/NacosClientAuthServiceImplTest.java
Labels: kind/feature, Summer2021

#6873 [ISSUE#5697]Add new monitor observability Nacos 2.0
  config/pom.xml
  config/src/main/java/com/alibaba/nacos/config/server/aspect/RequestLogAspect.java
  config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/MemoryMonitor.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/PrintMemoryTask.java
  config/src/main/java/com/alibaba/nacos/config/server/monitor/ThreadTaskQueueMonitorTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java
  core/pom.xml
  core/src/main/java/com/alibaba/nacos/core/monitor/MetricsMonitor.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/MetricsClientConnectionEventListener.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/filter/MetricsGrpcRequestCountFilter.java
  core/src/test/java/com/alibaba/nacos/core/monitor/MetricsMonitorTest.java
  metrics/pom.xml
  metrics/src/main/java/com/alibaba/nacos/metrics/manager/ConfigMetricsConstant.java
  metrics/src/main/java/com/alibaba/nacos/metrics/manager/CoreMetricsConstant.java
  metrics/src/main/java/com/alibaba/nacos/metrics/manager/MetricsManager.java
  metrics/src/main/java/com/alibaba/nacos/metrics/manager/NamingMetricsConstant.java
  naming/pom.xml
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftCore.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftStore.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/DefaultSelfUpgradeChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HttpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/MysqlHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/TcpSuperSenseProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/MysqlHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
  naming/src/main/java/com/alibaba/nacos/naming/push/UdpPushService.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/hook/NacosMonitorPushResultHook.java
  naming/src/test/java/com/alibaba/nacos/naming/monitor/MetricsMonitorTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTaskTest.java
  pom.xml
Labels: Summer2021

#6903 support issues #6645
  config/src/main/java/com/alibaba/nacos/config/server/Config.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
Labels: kind/enhancement, area/Nacos console, area/Config

#6916 [ISSUE #6894] add the unit test of com.alibaba.nacos.naming.remote.rpc.handler.
  naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/DistroDataRequestHandlerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandlerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceListRequestHandlerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandlerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandlerTest.java
Labels: area/Test

#6959 [ISSUE #5095] Add some testcases for common executor
  common/src/main/java/com/alibaba/nacos/common/executor/ExecutorFactory.java
  common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
  common/src/test/java/com/alibaba/nacos/common/event/ServerConfigChangeEventTest.java
  common/src/test/java/com/alibaba/nacos/common/executor/ExecutorFactoryTest.java
  common/src/test/java/com/alibaba/nacos/common/executor/NameThreadFactoryTest.java
  common/src/test/java/com/alibaba/nacos/common/executor/ThreadPoolManagerTest.java
Labels: area/Test

#6950 [ISSUE #5095] Add some testcases for common cache
  common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheBuilder.java
  common/src/test/java/com/alibaba/nacos/common/cache/builder/CacheBuilderTest.java
  common/src/test/java/com/alibaba/nacos/common/cache/decorators/AutoExpireCacheTest.java
  common/src/test/java/com/alibaba/nacos/common/cache/decorators/LruCacheTest.java
  common/src/test/java/com/alibaba/nacos/common/cache/decorators/SynchronizedCacheTest.java
  common/src/test/java/com/alibaba/nacos/common/cache/impl/SimpleCacheTest.java
Labels: area/Test

#6989 [ISSUE#5695] Summer2021 add unit test for CryptoManager
  api/src/test/java/com/alibaba/nacos/api/config/CryptoManagerTest.java
Labels: Summer2021

#6988 [ISSUE#5695] Summer2021 add unit test for AesCrypto
  client/src/test/java/com/alibaba/nacos/client/config/AesCryptoTest.java
Labels: Summer2021

#6996 [ISSUE#5696] add derby database
  auth/pom.xml
  auth/src/main/java/com/alibaba/nacos/auth/configuration/ConditionOnEmbeddedStorage.java
  auth/src/main/java/com/alibaba/nacos/auth/configuration/ConditionStandaloneEmbedStorage.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/AuthEmbeddedPermissionPersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/AuthEmbeddedRolePersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/AuthEmbeddedUserPersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/AuthExternalPermissionPersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/AuthExternalRolePersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/AuthExternalUserPersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/AuthDynamicDataSource.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/ExternalDataSourceServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/AuthEmbeddedStoragePersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/AuthStandaloneDatabaseOperateImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/BaseDatabaseOperate.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/DatabaseOperate.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/EmbeddedPaginationHelperImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/externel/AuthExternalStoragePersistServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/sql/EmbeddedStorageContextUtils.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/sql/ModifyRequest.java
  auth/src/main/resources/META-INF/spring.factories
  auth/src/test/java/com/alibaba/nacos/auth/persist/AuthEmbeddedPermissionPersistServiceImplTest.java
  auth/src/test/java/com/alibaba/nacos/auth/persist/AuthEmbeddedRolePersistServiceImplTest.java
  auth/src/test/java/com/alibaba/nacos/auth/persist/AuthEmbeddedUserPersistServiceImplTest.java
  auth/src/test/java/com/alibaba/nacos/auth/persist/AuthExternalPermissionPersistServiceImplTest.java
  auth/src/test/java/com/alibaba/nacos/auth/persist/AuthExternalRolePersistServiceImplTest.java
  auth/src/test/java/com/alibaba/nacos/auth/persist/AuthExternalUserPersistServiceImplTest.java
  auth/src/test/java/com/alibaba/nacos/auth/persist/datasource/DataSourcePoolPropertiesTest.java
Labels: Summer2021

#7004 [ISSUE#5696] Fix auth server type
  address/src/main/java/com/alibaba/nacos/address/auth/AddressServerAuthManager.java
  address/src/main/java/com/alibaba/nacos/address/configuration/AddressServerSpringConfiguration.java
  auth/src/main/java/com/alibaba/nacos/auth/NacosAuthConfig.java
  auth/src/main/java/com/alibaba/nacos/auth/NacosAuthServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
  auth/src/main/java/com/alibaba/nacos/auth/common/AuthSystemTypes.java
  auth/src/main/java/com/alibaba/nacos/auth/context/IdentityContext.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/datasource/ExternalDataSourceServiceImpl.java
  auth/src/main/java/com/alibaba/nacos/auth/persist/repository/embedded/AuthEmbeddedStoragePersistServiceImpl.java
  auth/src/main/resources/META-INF/services/com.alibaba.nacos.auth.AuthService
  auth/src/test/java/com/alibaba/nacos/auth/common/AuthConfigsTest.java
  auth/src/test/java/com/alibaba/nacos/auth/common/AuthPluginManagerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/auth/MockAuthManager.java
  console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/PermissionController.java
  console/src/main/java/com/alibaba/nacos/console/controller/RoleController.java
  console/src/main/java/com/alibaba/nacos/console/controller/UserController.java
  console/src/main/java/com/alibaba/nacos/console/filter/JwtAuthenticationTokenFilter.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/CustomAuthenticationProvider.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/JwtAuthenticationEntryPoint.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/JwtTokenManager.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/LdapAuthenticationProvider.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthConfig.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/NacosAuthManager.java
  console/src/main/java/com/alibaba/nacos/console/security/nacos/roles/NacosRoleServiceImpl.java
  console/src/main/resources/application.properties
  console/src/test/java/com/alibaba/nacos/console/controller/UserControllerTest.java
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
  core/src/test/java/com/alibaba/nacos/core/auth/AuthFilterTest.java
  distribution/conf/application.properties
Labels: Summer2021
