Repository alibaba/nacos, pull requests merged in 2021-01, with the labels that each got.

#4636 Support register persistent instance and tcp health check
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncData.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/HealthCheckInstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/HeartBeatInstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckReactor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/HealthCheckStatus.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatProcessorV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatUpdateTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceBeatChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckProcessorV2Delegate.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
  naming/src/test/java/com/alibaba/nacos/naming/JraftTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapperTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTaskTest.java
Labels: kind/feature

#4644 [ISSUE #4643] fix jraft response instance
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
Labels: kind/bug

#4635 [ISSUE-#4631] Remove timer,Use ScheduledThreadPoolExecutor replaced.
  client/src/main/java/com/alibaba/nacos/client/identify/CredentialWatcher.java
Labels: kind/code quality

#4651 onnectionLimitRule submit.client use same executor during different …
  api/src/main/java/com/alibaba/nacos/api/remote/request/RequestMeta.java
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/utils/AppNameUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifier.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMetaInfo.java
  core/src/main/java/com/alibaba/nacos/core/remote/event/ConnectionLimitRuleChangeEvent.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/remote/rsocket/RsocketRpcServer.java
Labels: kind/feature

#4632 upgrade axios version to 0.21.1
  console-ui/package.json
Labels: dependencies

#4656 Remove service cache data when service removed
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/EmptyServiceAutoCleanerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/Client.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/client/ClientOperationEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/metadata/MetadataEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/service/ServiceEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/PerformanceLoggerThread.java
  naming/src/test/java/com/alibaba/nacos/naming/core/SubscribeManagerTest.java
Labels: kind/enhancement

#4663 [ISSUE-#4662] Just choose one between nacosDomain mode and servers mode.
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
Labels: kind/enhancement

#4634 [ISSUE-#4631] Free credential instance when serverHttpAgent shutdown.
  client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/SpasAdapter.java
  client/src/main/java/com/alibaba/nacos/client/identify/CredentialWatcher.java
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
Labels: area/Client, kind/code quality

#4675 Add auth for naming rpc api and ix some bugs for 2.0.0
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientComponentRegistry.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTaskFailedHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceListRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/ServiceQueryRequestHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/SubscribeServiceRequestHandler.java
Labels: kind/bug

#4670 naming push service support CSharp client
  naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java
  naming/src/main/java/com/alibaba/nacos/naming/push/PushService.java
Labels: kind/feature

#4677 [ISSUE #4429] Fix mcp can't be open
  istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java
Labels: area/Istio, kind/bug

#4683 [ISSUE #4593] Add server identity to replace user-agent white list.
  auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
  auth/src/main/java/com/alibaba/nacos/auth/util/AuthHeaderUtil.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
  distribution/conf/application.properties
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
Labels: kind/enhancement

#4688 [ISSUE #4681] Fix miss line break for query config.
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
Labels: kind/bug

#4692 fix #4686
  api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
  api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigListener.java
  api/src/main/java/com/alibaba/nacos/api/config/annotation/NacosConfigurationProperties.java
Labels: area/Config, area/Spring, kind/refactor

#4703 [ISSUE #4701] Fix bypass authentication(identity) problem.
  console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/code/ControllerMethodsCache.java
Labels: kind/bug

#4666 [ISSUE #4661]configServletInner#doGetConfig code optimization
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
Labels: kind/code quality

#4728 Sync health check status for persistent instance.
  .gitignore
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/HealthCheckInstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/PersistentHealthStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2.java
Labels: kind/feature

#4733 Support update cluster metadata.
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperatorV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ClusterOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
Labels: kind/feature

#4736 Refactor naming client proxy to support auth
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientProxy.java
Labels: kind/feature, kind/refactor

#4753 Use SafeConstructor to parse yaml configuration
  .gitignore
  client/src/main/java/com/alibaba/nacos/client/config/impl/YmlChangeParser.java
  client/src/test/java/com/alibaba/nacos/client/config/listener/impl/YmlChangeParserTest.java
Labels: kind/enhancement, kind/refactor

#4778 make SecurityProxy.accessToken threadsafe in single writer multi reader
  client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java
  client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java
Labels: kind/enhancement, kind/refactor

#4764 [ISSUE-#4762] Naming health check thread num support user define it by self.
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalExecutor.java
Labels: kind/enhancement

#4802 fix-4787
  common/src/main/java/com/alibaba/nacos/common/utils/IPUtil.java
Labels: kind/bug

#4815 [ISSUE#4788]Fix client id judgement error for ipv6
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegateTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java
Labels: kind/bug, version/2.x

#4827 [ISSUE #4806] fix addListener method comment
  api/src/main/java/com/alibaba/nacos/api/config/ConfigService.java
Labels: kind/code quality

#4828 Full support for registering custom instances
  config/src/main/java/com/alibaba/nacos/config/server/monitor/ThreadTaskQueueMonitorTask.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/cleaner/ExpiredMetadataCleaner.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/metadata/MetadataEvent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ServiceStorage.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ExpiredMetadataInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/InstancePublishInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListener.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/InstanceEnableBeatCheckInterceptor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/UnhealthyInstanceChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/HealthCheckTaskV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/PersistentHealthStatusSynchronizer.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HealthCheckCommonV2.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/HttpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/MysqlHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/v2/processor/TcpHealthCheckProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/Constants.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java
  naming/src/test/java/com/alibaba/nacos/naming/BaseTest.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/persistent/impl/NamingSnapshotOperationTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/CatalogControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ClusterControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/DomainTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/DomainsManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTaskTest.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ClientBeatCheckTaskV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/healthcheck/interceptor/HealthCheckTaskInterceptWrapperTest.java
  naming/src/test/java/com/alibaba/nacos/naming/push/v2/NamingSubscriberServiceV2ImplTest.java
  naming/src/test/java/com/alibaba/nacos/naming/raft/RaftStoreTest.java
Labels: kind/enhancement

#4832 Adapt some naming openAPI
  naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV1Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/monitor/MetricsMonitor.java
  naming/src/main/java/com/alibaba/nacos/naming/web/DistroIpPortTagGenerator.java
Labels: kind/refactor
