Repository alibaba/nacos, pull requests merged in 2021-08, with the labels that each got.

#6513 [ISSUE #6510] fix the F1 cannot full screen.
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/bug

#6520 Refactor the cache to replace guava
  client/src/main/java/com/alibaba/nacos/client/config/impl/Limiter.java
  common/src/main/java/com/alibaba/nacos/common/cache/Cache.java
  common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheBuilder.java
  common/src/main/java/com/alibaba/nacos/common/cache/builder/CacheItemProperties.java
  common/src/main/java/com/alibaba/nacos/common/cache/decorators/AutoExpireCache.java
  common/src/main/java/com/alibaba/nacos/common/cache/decorators/LruCache.java
  common/src/main/java/com/alibaba/nacos/common/cache/decorators/SynchronizedCache.java
  common/src/main/java/com/alibaba/nacos/common/cache/impl/SimpleCache.java
  common/src/test/java/com/alibaba/nacos/common/cache/AutoExpireCacheTest.java
  common/src/test/java/com/alibaba/nacos/common/cache/LruCacheTest.java
  common/src/test/java/com/alibaba/nacos/common/cache/SimpleCacheTest.java
  core/src/main/java/com/alibaba/nacos/core/utils/StringPool.java
Labels: kind/refactor

#6528 [FOR #6487] [nacos-api] export the constant in the directory config.
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  api/src/main/java/com/alibaba/nacos/api/config/ConfigFactory.java
  api/src/main/java/com/alibaba/nacos/api/config/ConfigType.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/AbstractConfigRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ClientConfigMetricRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigChangeNotifyRequest.java
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/ConfigQueryRequest.java
Labels: kind/refactor

#6532 Replace "ThreadFactoryBuilder" API with jdk API and add unit test
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/utils/ThreadFactoryBuilder.java
  common/src/test/java/com/alibaba/nacos/common/utils/ThreadFactoryBuilderTest.java
  core/src/main/java/com/alibaba/nacos/core/utils/GlobalExecutor.java
Labels: kind/refactor

#6582 [ISSUE #6581] fix json deserialization error of ServiceController subscribers interface
  naming/src/main/java/com/alibaba/nacos/naming/pojo/Subscriber.java
Labels: kind/bug

#6574 [ISSUE #6347] Change the delete by page SQL to support the Derby.
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
Labels: kind/enhancement, area/Config

#6576 [ISSUE #6572] add client info for OperatorController metrics interface
  naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/OperatorControllerTest.java
Labels: kind/enhancement

#6617 [ISSUE #5095] Add unit test to HttpUtils
  common/src/test/java/com/alibaba/nacos/common/http/HttpUtilsTest.java
Labels: area/Test

#6616 Remove unused code; Use Camel-Case;Optimize if statement;
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
Labels: kind/code quality

#6639 FIX #6625 When switching namespaces, search criteria do not work
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
Labels: kind/bug, area/Nacos console

#6644 [ISSUE #6643] Add unit tests for package com.alibaba.nacos.naming.core.v2.service.
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImplTest.java
Labels: kind/refactor

#6593 [ISSUE#5696] Add auth plugin interface.
  auth/src/main/java/com/alibaba/nacos/auth/AuthPluginManager.java
  auth/src/main/java/com/alibaba/nacos/auth/AuthService.java
  auth/src/main/java/com/alibaba/nacos/auth/common/AuthConfigs.java
  auth/src/main/java/com/alibaba/nacos/auth/common/IdentifyPositionTypes.java
  auth/src/main/java/com/alibaba/nacos/auth/context/GrpcIdentityContextBuilder.java
  auth/src/main/java/com/alibaba/nacos/auth/context/HttpIdentityContextBuilder.java
  auth/src/main/java/com/alibaba/nacos/auth/context/IdentityContext.java
  auth/src/main/java/com/alibaba/nacos/auth/context/IdentityContextBuilder.java
  auth/src/main/java/com/alibaba/nacos/auth/exception/AuthConfigsException.java
  auth/src/main/resources/META-INF/services/com.alibaba.nacos.auth.AuthService
  auth/src/test/java/com/alibaba/nacos/auth/common/AuthConfigsTest.java
  auth/src/test/java/com/alibaba/nacos/auth/common/AuthPluginManagerTest.java
  auth/src/test/java/com/alibaba/nacos/auth/common/IdentityContextBuilderTest.java
  console/src/main/resources/application.properties
  distribution/conf/application.properties
  pom.xml
Labels: Summer2021

#6653 [ISSUE #6628] Remove redundant functional interfaces
  common/src/main/java/com/alibaba/nacos/common/http/AbstractHttpClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/notify/EventPublisherFactory.java
  common/src/main/java/com/alibaba/nacos/common/utils/BiConsumer.java
  common/src/main/java/com/alibaba/nacos/common/utils/BiFunction.java
  common/src/main/java/com/alibaba/nacos/common/utils/MapUtil.java
Labels: kind/refactor

#6733 Upgrade jraft version to 1.3.8
  pom.xml
Labels: dependencies
