Repository alibaba/nacos, pull requests merged in 2021-07, with the labels that each got.

#6217 Add SPI for upgrade checker.
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/DefaultSelfUpgradeChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/SelfUpgradeChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/SelfUpgradeCheckerSpiHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/MockSelfUpgradeChecker.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgementTest.java
  naming/src/test/resources/META-INF/services/com.alibaba.nacos.naming.core.v2.upgrade.SelfUpgradeChecker
Labels: kind/refactor

#6211 [ISSUE#3102] nacos-common module ArrayUtils、StringUtils
  common/src/main/java/com/alibaba/nacos/common/utils/ArrayUtils.java
  common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/ArrayUtilsTest.java
  common/src/test/java/com/alibaba/nacos/common/utils/StringUtilsTest.java
Labels: kind/refactor

#6237 [ISSUE #5092] Add unit tests for class ExternalUserPersistServiceImpl in nacos 2.0
  config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImplTest.java
Labels: area/Test

#6226 [FOR 5094 remote/grpc] add unit tests in nacos-core.
  core/pom.xml
  core/src/main/java/com/alibaba/nacos/core/remote/RpcAckCallbackSynchronizer.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
  core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptorTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptorTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcServerTest.java
  pom.xml
Labels: area/Test

#6227 Add NumberUtils、NumberUtilsTest;Modify NumberUtil dependency
  common/src/main/java/com/alibaba/nacos/common/utils/NumberUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/NumberUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/NumberUtilsTest.java
  core/src/main/java/com/alibaba/nacos/core/utils/RemoteUtils.java
Labels: kind/refactor

#6234 [FOR 5094 remote/core] add unit tests in nacos-core.
  core/src/test/java/com/alibaba/nacos/core/remote/core/RpcAckCallbackInitorOrCleanerTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/core/ServerLoaderInfoRequestHandlerTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/core/ServerReloaderRequestHandlerTest.java
Labels: area/Test

#6243 [ISSUE #6228] Add RandomUtils/RandomUtilsTest
  common/src/main/java/com/alibaba/nacos/common/utils/RandomUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/RandomUtilsTest.java
Labels: kind/refactor

#6247 [ISSUE #6240] Add TypeUtils/TypeUtilsTest
  common/src/main/java/com/alibaba/nacos/common/utils/TypeUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/TypeUtilsTest.java
Labels: kind/refactor

#6251 [ISSUE #5095] Add unit test for CollectionUtils
  common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java
Labels: area/Test

#6239 [ISSUE #6216] Unify SQL naming style.
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/EmbeddedUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/RowMapperManager.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalPermissionPersistServiceImplTest.java
  config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalRolePersistServiceImplTest.java
  config/src/test/java/com/alibaba/nacos/config/server/auth/ExternalUserPersistServiceImplTest.java
Labels: kind/refactor

#6298 [ISSUE#6272] Refactor Instance builder to build and handler request from http.
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/builder/InstanceBuilder.java
  api/src/main/java/com/alibaba/nacos/api/naming/spi/generator/IdGenerator.java
  api/src/test/java/com/alibaba/nacos/api/naming/pojo/builder/InstanceBuilderTest.java
  naming/src/main/java/com/alibaba/nacos/naming/constants/Constants.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/UpgradeOpsController.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Instance.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/DefaultSelfUpgradeChecker.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/AppExtensionHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilder.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/DefaultInstanceIdGenerator.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilder.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/InstanceExtensionHandler.java
  naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.pojo.instance.InstanceExtensionHandler
  naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilderTest.java
  naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/DefaultInstanceIdGeneratorTest.java
  naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilderTest.java
  naming/src/test/java/com/alibaba/nacos/naming/pojo/instance/MockInstanceExtensionHandler.java
  naming/src/test/resources/META-INF/services/com.alibaba.nacos.naming.pojo.instance.InstanceExtensionHandler
Labels: kind/refactor

#6307 [FOR 5094 controller] add unit tests in nacos-core.
  core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java
  core/src/test/java/com/alibaba/nacos/core/controller/CoreOpsControllerTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/ServerLoaderControllerTest.java
Labels: area/Test

#6313 [ISSUE #6302] replace common-lang3 in nacos-sys module
  sys/src/main/java/com/alibaba/nacos/sys/env/EnvUtil.java
  sys/src/main/java/com/alibaba/nacos/sys/env/NacosAutoRefreshPropertySourceLoader.java
  sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
Labels: kind/refactor

#6315 [ISSUE #6303] replace commons-lang3 in nacos-test module
  test/core-test/src/test/java/com/alibaba/nacos/test/common/WatchFileCenter_ITCase.java
  test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/MemberLookup_ITCase.java
  test/naming-test/src/test/java/com/alibaba/nacos/test/naming/ClientBeat_ITCase.java
Labels: kind/refactor

#6327 [ISSUE #5095] Add unit test for ClassUtils
  common/src/main/java/com/alibaba/nacos/common/utils/ClassUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/ClassUtilsTest.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
Labels: area/Test

#6300 Use StringBuilder#append(Char) to improve performance
  address/src/main/java/com/alibaba/nacos/address/component/AddressServerGeneratorManager.java
  address/src/test/java/com/alibaba/nacos/address/SimpleHttpTestUtils.java
  client/src/main/java/com/alibaba/nacos/client/utils/EnvUtil.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpUtils.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Query.java
  common/src/main/java/com/alibaba/nacos/common/task/engine/NacosExecuteTaskExecuteEngine.java
  common/src/main/java/com/alibaba/nacos/common/utils/ExceptionUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/TypeUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/manager/TaskManager.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/SwitchService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/MD5Util.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/RegexParser.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/SimpleFlowData.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/remote/control/TpsMonitorManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Instances.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Service.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java
  naming/src/main/java/com/alibaba/nacos/naming/web/NamingResourceParser.java
  test/naming-test/src/test/java/com/alibaba/nacos/test/naming/NamingBase.java
Labels: kind/refactor

#6332 [ISSUE#6295] Fix instance metadata will not be removed for ip port client.
  naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java
Labels: kind/bug

#6387 [ISSUE #6386] Stop v1 distro verification when cluster upgraded to v2.
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/component/DistroDataStorageImpl.java
Labels: kind/enhancement

#6383 [ISSUE #6365] Implement the built-in Selector in Nacos 1.x and add unit test.
  api/src/main/java/com/alibaba/nacos/api/naming/selector/AbstractCmdbSelector.java
  api/src/main/java/com/alibaba/nacos/api/naming/selector/Selector.java
  api/src/main/java/com/alibaba/nacos/api/naming/selector/context/CmdbContext.java
  naming/src/main/java/com/alibaba/nacos/naming/selector/CmdbLabelSelector.java
  naming/src/main/java/com/alibaba/nacos/naming/selector/SelectorManager.java
  naming/src/main/java/com/alibaba/nacos/naming/selector/context/CmdbSelectorContextBuilder.java
  naming/src/main/resources/META-INF/services/com.alibaba.nacos.api.naming.selector.Selector
  naming/src/main/resources/META-INF/services/com.alibaba.nacos.api.naming.selector.context.SelectorContextBuilder
  naming/src/test/java/com/alibaba/nacos/naming/selector/CmdbLabelSelectorTest.java
  naming/src/test/java/com/alibaba/nacos/naming/selector/MockCmdbContextBuilder.java
  naming/src/test/java/com/alibaba/nacos/naming/selector/MockSelector.java
Labels: kind/feature, kind/refactor

#6395 [ISSUE#6384] Add redo feature for nacos client naming
  client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListener.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoService.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/RedoScheduledTask.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/InstanceRedoData.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/RedoData.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/redo/data/SubscriberRedoData.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcConnectionEventListenerTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/NamingGrpcRedoServiceTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/redo/RedoScheduledTaskTest.java
Labels: kind/feature

#6423 [BUG]Fix yaml parse concurrent problem
  config/src/main/java/com/alibaba/nacos/config/server/utils/YamlParserUtil.java
Labels: kind/bug

#6409 [ISSUE #6382] Fix the Algorithm HmacSHA256 not available error when login
  distribution/bin/startup.sh
Labels: kind/bug

#6422 [ISSUE#6403] the expired time of naming client can be configured.
  core/src/main/java/com/alibaba/nacos/core/config/AbstractDynamicConfig.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/DistroConfig.java
  core/src/test/java/com/alibaba/nacos/core/distributed/distro/DistroConfigTest.java
  distribution/conf/application.properties
  distribution/conf/application.properties.example
  naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/ClientConfig.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushConfig.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClientTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/IpPortBasedClientTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/misc/ClientConfigTest.java
Labels: kind/enhancement

#6453 [ISSUE #5095] Add unit test for TlsFileWatcher
  common/src/main/java/com/alibaba/nacos/common/tls/TlsFileWatcher.java
  common/src/test/java/com/alibaba/nacos/common/tls/TlsFileWatcherTest.java
Labels: area/Test

#6366 improvement currentTimeMillis calc, using System.nanoTime() to measur…
  core/src/main/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGenerator.java
  core/src/test/java/com/alibaba/nacos/core/distributed/id/SnowFlowerIdGeneratorTest.java
Labels: kind/refactor

#6404 [Reduce dependence]>[Lists] Replace "google.common.collect.*" API wit…
  common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  core/src/test/java/com/alibaba/nacos/core/remote/control/TpsMonitorManagerTest.java
  naming/src/main/java/com/alibaba/nacos/naming/core/HealthOperatorV1Impl.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
Labels: kind/refactor

#6471 [ISSUE #5095] Add unit test for RpcClientFactory
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
Labels: area/Test

#6443 [Reduce dependence]>[Maps] Replace "google.common.collect.*" API with…
  common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerListManager.java
  naming/src/test/java/com/alibaba/nacos/naming/core/ServiceManagerTest.java
Labels: kind/refactor

#6490 [ISSUE #5093] Add unit tests for module nacos-consistency in nacos 2.0.
  consistency/src/test/java/com/alibaba/nacos/consistency/ProtoMessageUtilTest.java
  consistency/src/test/java/com/alibaba/nacos/consistency/SerializeFactoryTest.java
  consistency/src/test/java/com/alibaba/nacos/consistency/serialize/JacksonSerializerTest.java
  consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/LocalFileMetaTest.java
  consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/ReaderTest.java
  consistency/src/test/java/com/alibaba/nacos/consistency/snapshot/WriterTest.java
  core/src/test/java/com/alibaba/nacos/core/remote/ConnectionManagerTest.java
Labels: area/Test

#6496 [ISSUE #6296] optimize the new config page, skip to config list page when create the config successfully.
  console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, kind/enhancement

#6500 replace "google.common.base.Stopwatch" API with Spring API
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/CapacityService.java
Labels: kind/refactor

#6445 [Reduce dependence]>[Sets] Replace "google.common.collect.*" API with…
  common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
  common/src/main/java/com/alibaba/nacos/common/utils/ConvertUtils.java
  common/src/test/java/com/alibaba/nacos/common/utils/CollectionUtilsTest.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
Labels: kind/refactor

#6502 replace "google.common.base.Preconditions" API with jdk API
  common/src/main/java/com/alibaba/nacos/common/utils/Preconditions.java
  common/src/test/java/com/alibaba/nacos/common/utils/PreconditionsTest.java
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceProperties.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
Labels: kind/refactor
