Repository alibaba/nacos, pull requests merged in 2021-02, with the labels that each got.

#4845 Add switch to close double write in 2.0.0
  common/src/main/java/com/alibaba/nacos/common/task/engine/NacosDelayTaskExecuteEngine.java
  consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/UpgradeJudgement.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/delay/DoubleWriteEventListener.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/upgrade/doublewrite/execute/AsyncServicesCheckTask.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchDomain.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchEntry.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchManager.java
Labels: kind/feature

#4866 [ISSUE #3876] [NA] failed to update serviceName: DEFAULT_GROUP@@prod-…
  client/src/main/java/com/alibaba/nacos/client/naming/core/HostReactor.java
Labels: kind/enhancement

#4872 move server loader controller from console to core; modify common server scheduler count to solve large cpu usage
  api/src/main/java/com/alibaba/nacos/api/remote/RpcScheduledExecutor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java
  core/src/main/java/com/alibaba/nacos/core/utils/Commons.java
Labels: kind/bug, kind/refactor

#4875 optimize config file read
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
Labels: kind/bug

#4870 [ISSUE-#4854] Modify Header to support Keys Ignore Case
  common/src/main/java/com/alibaba/nacos/common/http/client/response/JdkHttpClientResponse.java
  common/src/main/java/com/alibaba/nacos/common/http/param/Header.java
  common/src/test/java/com/alibaba/nacos/common/http/param/HeaderTest.java
Labels: kind/bug

#4882 listen config auth bugfix
  config/src/main/java/com/alibaba/nacos/config/server/auth/ConfigResourceParser.java
Labels: kind/bug

#4883 Fix getSpasHeaders serviceName exception
  client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java
Labels: kind/bug

#4922 Add ClientFactory to extend client
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/PersistentServiceProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/StandalonePersistentServiceProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftConsistencyServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft/RaftListener.java
  naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/constants/Constants.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/PersistentIpPortClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/ClientOperationService.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/GlobalConfig.java
  naming/src/main/java/com/alibaba/nacos/naming/push/UdpPushService.java
  naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java
  naming/src/main/java/com/alibaba/nacos/naming/utils/InstanceUtil.java
  naming/src/main/resources/META-INF/services/com.alibaba.nacos.naming.core.v2.client.factory.ClientFactory
Labels: kind/refactor

#4919 [ISSUE #4917] Raft ops interface add auth
  core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java
Labels: kind/enhancement

#4935 Add spi for PushExecutor to support extend
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/SpiImplPushExecutorHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/SpiPushExecutor.java
Labels: kind/refactor

#4938 Wrapper push data make executors can do operation.
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/PushDataWrapper.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutor.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorRpcImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/executor/PushExecutorUdpImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/push/v2/task/PushExecuteTask.java
Labels: kind/refactor

#4951 Add EphemeralIpPortClientManager unit test
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java
Labels: area/Test

#4947 tag publish bugfix; ignore server port for connection reset request.
  api/src/main/java/com/alibaba/nacos/api/config/remote/request/cluster/ConfigChangeClusterSyncRequest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClient.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
Labels: kind/bug

#4961 Add ClientSyncAttributes to sync some client metadata to other server.
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/constants/ClientConstants.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncAttributes.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/ClientSyncData.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/ClientFactoryHolder.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/ConnectionBasedClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/EphemeralIpPortClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/factory/impl/PersistentIpPortClientFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/ConnectionBasedClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/PersistentIpPortClientManager.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManagerTest.java
Labels: kind/refactor
