Repository alibaba/nacos, pull requests merged in 2022-08, with the labels that each got.

#8881 [ISSUE #8880] add a request exception handler
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: kind/bug, area/Nacos console

#8911 [ISSUE#8910] bug fix calcu ipCount
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
Labels: kind/bug

#8940 [ISSUE #8931] Fix bug :BatchInstanceData cannot Serializable question
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/BatchInstanceData.java
Labels: kind/bug

#8956 optimize: internationalization of product description content
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/Login/Login.jsx
  console-ui/src/pages/Login/index.scss
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console

#8847 For #8310, add nacos-address-plugin module
  common/src/main/java/com/alibaba/nacos/common/utils/CollectionUtils.java
  core/pom.xml
  core/src/main/java/com/alibaba/nacos/core/cluster/address/ServerConfAddressPlugin.java
  core/src/main/java/com/alibaba/nacos/core/cluster/address/StandAloneAddressPlugin.java
  core/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.address.spi.AddressPlugin
  core/src/test/java/com/alibaba/nacos/core/cluster/address/ServerConfAddressPluginTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/address/StandAloneAddressPluginTest.java
  plugin/address/pom.xml
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/common/AddressProperties.java
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/exception/AddressException.java
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/impl/EndpointAddressPlugin.java
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/impl/PropertyAddressPlugin.java
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AbstractAddressPlugin.java
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AddressPlugin.java
  plugin/address/src/main/java/com/alibaba/nacos/plugin/address/spi/AddressPluginManager.java
  plugin/address/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.address.spi.AddressPlugin
  plugin/address/src/test/java/com/alibaba/nacos/plugin/address/common/AddressPropertiesTest.java
  plugin/address/src/test/java/com/alibaba/nacos/plugin/address/exception/AddressExceptionTest.java
  plugin/address/src/test/java/com/alibaba/nacos/plugin/address/impl/EndpointAddressPluginTest.java
  plugin/address/src/test/java/com/alibaba/nacos/plugin/address/impl/PropertyAddressPluginTest.java
  plugin/address/src/test/java/com/alibaba/nacos/plugin/address/spi/AddressPluginManagerTest.java
  plugin/pom.xml
  pom.xml
Labels: Summer2022
