Repository alibaba/nacos, pull requests merged in 2022-09, with the labels that each got.

#9059 for [issue#8308], fix NacosApiException
  api/src/main/java/com/alibaba/nacos/api/exception/api/NacosApiException.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
  config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigControllerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ConfigOperationServiceTest.java
  console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2.java
  console/src/main/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandler.java
  console/src/main/java/com/alibaba/nacos/console/service/NamespaceOperationService.java
  console/src/test/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2Test.java
  console/src/test/java/com/alibaba/nacos/console/service/NamespaceOperationServiceTest.java
Labels: Summer2022

#9066 for [issue #8308] update NacosClusterControllerV2
  core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterControllerV2.java
  core/src/main/java/com/alibaba/nacos/core/service/NacosClusterOperationService.java
  core/src/test/java/com/alibaba/nacos/core/controller/v2/NacosClusterControllerV2Test.java
  core/src/test/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2ControllerTest.java
  core/src/test/java/com/alibaba/nacos/core/service/NacosClusterOperationServiceTest.java
Labels: Summer2022

#9093 [ISSUE #9013] Enhance Rpc config related to one RpcClientConfig
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstants.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcSdkClient.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientTest.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstantsTest.java
Labels: area/Client

#9108 [ISSUE#9013] Do some refactor for readability.
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcConstants.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClientTest.java
Labels: kind/refactor

#9084 Commit ConfigInfoMapper.
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
Labels: Summer2022

#9112 [ISSUE#8312] Update ConfigInfoMapper and create ConfigInfoAggrMapper.
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
Labels: Summer2022

#9118 [ISSUE #8312] Create ConfigInfoBetaMapper.(#8312)
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
Labels: Summer2022

#9119 [ISSUE #8312] Add more mapper.
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/GroupCapacityMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantCapacityMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantInfoMapper.java
Labels: Summer2022

#9009 [ISSUE #8310] complete server addressing in plugin way
  config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerTest.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
  core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterV2Controller.java
Labels: Summer2022

#9111 [ISSUE#8308] update InstanceControllerV2 for api 2.0
  api/src/main/java/com/alibaba/nacos/api/naming/utils/NamingUtils.java
  api/src/test/java/com/alibaba/nacos/api/naming/utils/NamingUtilsTest.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/UtilsAndCommons.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/InstanceForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/InstanceMetadataBatchOperationForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/vo/InstanceDetailInfoVo.java
  naming/src/main/java/com/alibaba/nacos/naming/model/vo/InstanceMetadataBatchOperationVo.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2Test.java
Labels: Summer2022

#9145 [ISSUE #8312]Update all mapper.
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/GroupCapacityMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantCapacityMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/TenantInfoMapper.java
Labels: Summer2022

#9159 [ISSUE #8312]Update the mysql implementation.
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java
Labels: Summer2022

#9156 update ServiceControllerV2, add OperatorControllerV2
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/HealthControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/OperatorControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/ServiceForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateHealthForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateSwitchForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/vo/MetricsInfoVo.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/OperatorControllerV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2Test.java
Labels: Summer2022

#8991 [ISSUE #8622] 移除 environment 概念
  client/src/main/java/com/alibaba/nacos/client/constant/Constants.java
  client/src/main/java/com/alibaba/nacos/client/env/AbstractPropertySource.java
  client/src/main/java/com/alibaba/nacos/client/env/DefaultSettingPropertySource.java
  client/src/main/java/com/alibaba/nacos/client/env/JvmArgsPropertySource.java
  client/src/main/java/com/alibaba/nacos/client/env/NacosClientProperties.java
  client/src/main/java/com/alibaba/nacos/client/env/NacosEnvironmentFactory.java
  client/src/main/java/com/alibaba/nacos/client/env/NacosEnvs.java
  client/src/main/java/com/alibaba/nacos/client/env/PropertiesPropertySource.java
  client/src/main/java/com/alibaba/nacos/client/env/PropertySourceSearch.java
  client/src/main/java/com/alibaba/nacos/client/env/SearchableEnvironment.java
  client/src/main/java/com/alibaba/nacos/client/env/SearchableProperties.java
  client/src/main/java/com/alibaba/nacos/client/env/SourceType.java
  client/src/main/java/com/alibaba/nacos/client/env/SystemEnvPropertySource.java
  client/src/test/java/com/alibaba/nacos/client/env/NacosClientPropertiesTest.java
  client/src/test/java/com/alibaba/nacos/client/env/NacosEnvironmentFactoryTest.java
  client/src/test/java/com/alibaba/nacos/client/env/NacosEnvsTest.java
Labels: kind/enhancement

#9193 [ISSUE#9060] Fix print logs for NamingTraceEvent.
  common/src/main/java/com/alibaba/nacos/common/notify/Event.java
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
  common/src/main/java/com/alibaba/nacos/common/trace/event/naming/NamingTraceEvent.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherTest.java
Labels: kind/enhancement, plugin

#9104 [ISSUE #8310] complete client addressing in plugin way
  client/pom.xml
  client/src/main/java/com/alibaba/nacos/client/address/AbstractServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/address/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/config/http/ServerHttpAgent.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigTransportClient.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java
  client/src/test/java/com/alibaba/nacos/client/config/NacosConfigServiceTest.java
  client/src/test/java/com/alibaba/nacos/client/config/http/ServerHttpAgentTest.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/core/ServerListManagerTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxyTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/ServerListFactory.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  pom.xml
Labels: Summer2022

#9127 Feature #8941 Support Fuzzy Query in Authority Control--for ui change.
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/AuthorityControl/PermissionsManagement/PermissionsManagement.js
  console-ui/src/pages/AuthorityControl/RolesManagement/RolesManagement.js
  console-ui/src/pages/AuthorityControl/UserManagement/UserManagement.js
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, plugin

#9212 For #8611, Close old datasource connection.
  config/src/main/java/com/alibaba/nacos/config/server/service/datasource/ExternalDataSourceServiceImpl.java
Labels: kind/enhancement

#9228 [ISSUE#8650] Make cluster/report both receive and send metadata.
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/DefaultGrpcClientConfig.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
Labels: kind/enhancement

#9233 [ISSUE #9227] fix subscriber scopeMatches
  common/src/main/java/com/alibaba/nacos/common/notify/listener/Subscriber.java
Labels: kind/bug

#9237 fix api result
  config/src/main/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2.java
  console/src/main/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/HealthControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2Test.java
Labels: Summer2022

#9220 [ISSUE #8309] Sync services and endpoints from k8s
  console/pom.xml
  console/src/main/resources/application.properties
  distribution/conf/application.properties
  distribution/conf/application.properties.example
  distribution/conf/nacos-logback.xml
  k8s-sync/pom.xml
  k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncConfig.java
  k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncServer.java
  k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/Loggers.java
  pom.xml
Labels: Summer2022

#9239 [ISSUE#9210] ConnectionBasedClient support add revision
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/AbstractClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClient.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/pojo/BatchInstancePublishInfo.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/AbstractClientTest.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/MockAbstractClient.java
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/client/impl/ConnectionBasedClientTest.java
Labels: kind/enhancement

#9226 [ISSUE #8312]Finish the datasource plugin.
  config/pom.xml
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedPaginationHelperImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePaginationHelperImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/MapperManager.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/constants/DataSourceConstant.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoAggrMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoBetaMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/HistoryConfigInfoMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoAggrMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoBetaMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoTagMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/HistoryConfigInfoMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoAggrMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoBetaMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoTagMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/HistoryConfigInfoMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/Mapper.java
  plugin/datasource/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.datasource.mapper.Mapper
Labels: Summer2022
