Repository alibaba/nacos, pull requests merged in 2023-12, with the labels that each got.

#11465 [ISSUES #11459] fix CONFIG_INFO_STATE_WRAPPER_ROW_MAPPER missing
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/ConfigRowMapperInjector.java
Labels: kind/bug, area/Config

#11453 fix(#11306): change the length of the field named resource from 255 to 128.
  distribution/conf/mysql-schema.sql
Labels: kind/enhancement

#11417 fix: connection count of current node is not accurate
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  core/src/main/java/com/alibaba/nacos/core/remote/NacosRuntimeConnectionEjector.java
Labels: kind/enhancement

#11207 Nacos客户端磁盘降级需求 issues:11053
  client/pom.xml
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverData.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverDataSource.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverReactor.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/FailoverSwitch.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/NamingFailoverData.java
  client/src/main/java/com/alibaba/nacos/client/naming/backups/datasource/DiskFailoverDataSource.java
  client/src/main/java/com/alibaba/nacos/client/naming/cache/ServiceInfoHolder.java
  client/src/main/java/com/alibaba/nacos/client/naming/utils/CacheDirUtil.java
  client/src/main/resources/META-INF/services/com.alibaba.nacos.client.naming.backups.FailoverDataSource
  client/src/test/java/com/alibaba/nacos/client/naming/backups/FailoverReactorTest.java
  client/src/test/java/com/alibaba/nacos/client/naming/backups/datasource/DiskFailoverDataSourceTest.java
Labels: kind/feature

#11326 [ISSUE #11325]Fix logging for Config pull events.
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigServletInner.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/trace/ConfigTraceService.java
Labels: area/Config, area/Client

#11514 check server stream ready state to avoid bytebuffer back up in flow control pending write queue.
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistService.java
  config/src/test/java/com/alibaba/nacos/config/server/configuration/ConfigCommonConfigTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/CommunicationControllerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigOpsControllerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
  config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandlerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigRemoveRequestHandlerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/remote/RpcConfigChangeNotifierTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/DiskServiceUnitTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/capacity/GroupCapacityPersistServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/capacity/TenantCapacityPersistServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/DiskUtilsTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/MD5UtilTest.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMeta.java
  core/src/main/java/com/alibaba/nacos/core/remote/NacosRuntimeConnectionEjector.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcConnection.java
  core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcConnectionTest.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/GroupCapacityMapper.java
Labels: kind/enhancement, kind/feature, area/Nacos Core

#11248 优化增量对账，减少开销
  config/src/main/java/com/alibaba/nacos/config/server/constant/PropertiesConstant.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpChangeConfigWorker.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ConfigExecutor.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
  plugin/datasource/src/test/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySqlTest.java
Labels: kind/enhancement, area/Config

#11521 fix config test case and remove useless code
  config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/ApplicationPublishRecord.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/GroupKey.java
  config/src/main/java/com/alibaba/nacos/config/server/model/app/MonitorInfo.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigSubService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpRequest.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/DumpService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllBetaProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllTagProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/processor/DumpProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifySingleService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTask.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/NotifyTaskProcessor.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/PersistService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoAggrPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoBetaPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoTagPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedHistoryConfigInfoPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/sql/ExternalStorageUtils.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/DiskUtil.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigServletInnerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandlerTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpProcessorTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/DumpProcessorUserRwaDiskTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/TestCaseUtils.java
  core/src/test/java/com/alibaba/nacos/core/remote/grpc/GrpcConnectionTest.java
  test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyImport_CITCase.java
  test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java
Labels: kind/refactor, area/Config, area/Test

#11508 [ISSUES #11499] fix address server health check error
  config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/HealthControllerTest.java
Labels: kind/bug

#11500 fix(#11498): fix CheckDbHealthTask.
  persistence/src/main/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceServiceImpl.java
  persistence/src/test/java/com/alibaba/nacos/persistence/datasource/ExternalDataSourceServiceImplTest.java
Labels: area/Config

#11427 support metric for grpc server request
  core/src/main/java/com/alibaba/nacos/core/monitor/MetricsMonitor.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcRequestAcceptor.java
Labels: kind/feature
