Repository alibaba/nacos, pull requests merged in 2024-04, with the labels that each got.

#11850 [ISSUE #11847] fix OpenApi publish Cas fail
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
  config/src/test/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImplTest.java
Labels: kind/bug, area/Config

#11913 Bump console ui dependencies to solve security problem with audit fix.
  console-ui/package-lock.json
Labels: dependencies

#11927 [ISSUE #11847] Feature: add console-ui publish config cas
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: area/Nacos console, area/Config

#11914 fix: vulnerability
  pom.xml
Labels: dependencies

#11945 [ISSUE #11943] 记录导入配置用户
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
Labels: kind/enhancement

#11942 [ISSUE #11879] Fix Navigator clipboard api needs a secure context (https)
  console-ui/src/components/Copy/index.jsx
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: kind/bug, area/Nacos console

#11940 [ISSUE #11902] Fix request and response reflect-config.json
  client/src/main/resources/META-INF/native-image/com.alibaba.nacos/nacos-client/reflect-config.json
Labels: kind/bug, area/Client

#12003 fix: CVE-2024-22262 Upgrade Spring to 5.3.34 (#11980)
  pom.xml
Labels: dependencies

#11976 [#11975] clean code , remove unused dependency javatuple
  consistency/pom.xml
  consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
  core/pom.xml
  naming/pom.xml
  pom.xml
Labels: kind/code quality, dependencies

#12021 update spring-boot-dependencies version to 2.7.18
  pom.xml
Labels: dependencies
