Repository alibaba/nacos, pull requests merged in 2024-03, with the labels that each got.

#11777 use npm audit fix to solve some ui security dependencies.
  console-ui/package-lock.json
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: dependencies

#11783 [ISSUE #11782] Optimized the use of map
  auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java
  client/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialService.java
  common/src/main/java/com/alibaba/nacos/common/spi/NacosServiceLoader.java
  common/src/main/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisher.java
  common/src/main/java/com/alibaba/nacos/common/trace/publisher/TraceEventPublisherFactory.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeListenContext.java
  consistency/src/main/java/com/alibaba/nacos/consistency/ProtocolMetaData.java
  consistency/src/main/java/com/alibaba/nacos/consistency/Serializer.java
  core/src/main/java/com/alibaba/nacos/core/distributed/distro/monitor/DistroRecordsHolder.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionManager.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/PersistentNotifier.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/ServiceManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisher.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/event/publisher/NamingEventPublisherFactory.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManager.java
  naming/src/main/java/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataManager.java
Labels: kind/code quality

#11801 PageHandlerAdapterFactory， handlerAdapters，handlerAdapterMap should unmodifiable
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/handler/PageHandlerAdapterFactory.java
Labels: kind/enhancement

#11822 :bug: Uncontrolled data used in path expression
  common/src/main/java/com/alibaba/nacos/common/utils/StringUtils.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java
Labels: kind/enhancement

#11844 feature: add client labels collect and attach labels to conn
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ClientWorkerTest.java
  common/src/main/java/com/alibaba/nacos/common/labels/LabelsCollector.java
  common/src/main/java/com/alibaba/nacos/common/labels/LabelsCollectorManager.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/AbstractLabelsCollector.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollector.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollectorManager.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/AbstractConfigGetter.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/ConfigGetterManager.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/EnvConfigGetter.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/JvmConfigGetter.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/OrderedConfigGetter.java
  common/src/main/java/com/alibaba/nacos/common/labels/impl/utils/PropertiesConfigGetter.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/main/java/com/alibaba/nacos/common/utils/ConnLabelsUtils.java
  common/src/main/resources/META-INF/services/com.alibaba.nacos.common.labels.LabelsCollector
  common/src/test/java/com/alibaba/nacos/common/labels/impl/ConfigGetterManagerTest.java
  common/src/test/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollectorManagerTest.java
  common/src/test/java/com/alibaba/nacos/common/labels/impl/Test1LabelsCollector.java
  common/src/test/java/com/alibaba/nacos/common/labels/impl/Test2LabelsCollector.java
  common/src/test/java/com/alibaba/nacos/common/utils/ConnLabelsUtilsTest.java
  common/src/test/resources/META-INF/services/com.alibaba.nacos.common.labels.LabelsCollector
  core/src/main/java/com/alibaba/nacos/core/remote/Connection.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMeta.java
Labels: kind/feature, area/Config, area/Client

#11875 :arrow_up: upgrade mysql-connector-java from 8.0.28 to 8.0.33
  common/pom.xml
  naming/pom.xml
  persistence/pom.xml
  pom.xml
Labels: dependencies

#11860 Update reflect-config.json
  client/src/main/resources/META-INF/native-image/com.alibaba.nacos/nacos-client/reflect-config.json
Labels: kind/enhancement, area/Client
