Repository alibaba/nacos, pull requests merged in 2024-11, with the labels that each got.

#12813 Summer ospp#12017 refactor controller
  config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
  config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigForm.java
  config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigFormV3.java
  config/src/main/java/com/alibaba/nacos/config/server/paramcheck/ConfigBlurSearchHttpParamExtractor.java
  config/src/main/java/com/alibaba/nacos/config/server/paramcheck/ConfigDefaultHttpParamExtractor.java
  console-ui/src/components/EditorNameSpace/EditorNameSpace.js
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/ConfigRollback/ConfigRollback.js
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console-ui/src/pages/ConfigurationManagement/HistoryDetail/HistoryDetail.js
  console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
  console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js
  console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleHealthController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleServerStateController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleInstanceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceController.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/naming/ServiceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/naming/ServiceHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/ServiceProxy.java
  console/src/main/resources/application.properties
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
  console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java
  console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryControllerTest.java
  console/src/test/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterControllerTest.java
  console/src/test/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceControllerTest.java
  console/src/test/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleInstanceControllerTest.java
  console/src/test/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceControllerTest.java
  console/src/test/java/com/alibaba/nacos/console/paramcheck/ParamExtractorTest.java
  core/src/main/java/com/alibaba/nacos/core/model/form/AggregationForm.java
  core/src/main/java/com/alibaba/nacos/core/model/form/NacosForm.java
  core/src/main/java/com/alibaba/nacos/core/model/form/PageForm.java
  core/src/main/java/com/alibaba/nacos/core/namespace/model/form/CreateNamespaceForm.java
  core/src/main/java/com/alibaba/nacos/core/namespace/model/form/NamespaceForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/ServiceForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/ServiceListForm.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateClusterForm.java
Labels: kind/refactor

#12830 [Refactor] Deprecated old api and default disabled old console api.
  api/src/main/java/com/alibaba/nacos/api/model/v2/ErrorCode.java
  auth/src/main/java/com/alibaba/nacos/auth/annotation/Secured.java
  auth/src/main/java/com/alibaba/nacos/auth/enums/ApiType.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CapacityController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ClientMetricsController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HealthController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v2/HistoryControllerV2.java
  console/src/main/java/com/alibaba/nacos/console/controller/HealthController.java
  console/src/main/java/com/alibaba/nacos/console/controller/NamespaceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v2/HealthControllerV2.java
  console/src/main/java/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleInstanceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceController.java
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/auth/RemoteRequestAuthFilter.java
  core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java
  core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
  core/src/main/java/com/alibaba/nacos/core/controller/ServerLoaderController.java
  core/src/main/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityConfig.java
  core/src/main/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityFilter.java
  core/src/main/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilitySpringConfig.java
  core/src/main/java/com/alibaba/nacos/core/controller/compatibility/Compatibility.java
  core/src/main/java/com/alibaba/nacos/core/controller/v2/CoreOpsV2Controller.java
  core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterControllerV2.java
  core/src/test/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityConfigTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityFilterTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilitySpringConfigTest.java
  distribution/conf/application.properties
  naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/HealthController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/OperatorController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/ServiceController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/CatalogControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ClientInfoControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/HealthControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/OperatorControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/PermissionController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/RoleController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
  plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/ApiType.java
Labels: kind/refactor

#12851 Cluster grpc request add server identity info.
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
  core/src/test/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxyTest.java
Labels: kind/enhancement, kind/refactor

#12871 Refactor Auth server identity check.
  auth/src/main/java/com/alibaba/nacos/auth/AbstractProtocolAuthService.java
  auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java
  auth/src/main/java/com/alibaba/nacos/auth/HttpProtocolAuthService.java
  auth/src/main/java/com/alibaba/nacos/auth/ProtocolAuthService.java
  auth/src/main/java/com/alibaba/nacos/auth/serveridentity/DefaultChecker.java
  auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentity.java
  auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityChecker.java
  auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolder.java
  auth/src/main/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityResult.java
  auth/src/test/java/com/alibaba/nacos/auth/GrpcProtocolAuthServiceTest.java
  auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java
  auth/src/test/java/com/alibaba/nacos/auth/serveridentity/ServerIdentityCheckerHolderTest.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClusterClient.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2Test.java
  console/src/main/resources/application.properties
  core/src/main/java/com/alibaba/nacos/core/auth/AuthFilter.java
  core/src/test/java/com/alibaba/nacos/core/auth/AuthFilterTest.java
Labels: kind/refactor

#12874 Remove excess code.(related issue #12871 )
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
Labels: kind/bug, area/Nacos console

#12875 fix type search on mysql model
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
Labels: kind/bug, area/Config

#12887 V3.0 develop unified defualt namespace
  client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
  common/src/main/java/com/alibaba/nacos/common/utils/NamespaceUtil.java
  common/src/test/java/com/alibaba/nacos/common/utils/NamespaceUtilTest.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ClientMetricsController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/HistoryController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ListenerController.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v2/ConfigControllerV2.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigRemoveRequestHandler.java
  console-ui/src/components/NameSpaceList/NameSpaceList.js
  console-ui/src/pages/ConfigurationManagement/ConfigDetail/ConfigDetail.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/ConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/ConfigEditor/NewConfigEditor.js
  console-ui/src/pages/ConfigurationManagement/ConfigRollback/ConfigRollback.js
  console-ui/src/pages/ConfigurationManagement/ConfigSync/ConfigSync.js
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console-ui/src/pages/ConfigurationManagement/HistoryDetail/HistoryDetail.js
  console-ui/src/pages/ConfigurationManagement/HistoryRollback/HistoryRollback.js
  console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js
  console-ui/src/pages/ConfigurationManagement/NewConfig/NewConfig.js
  console-ui/src/pages/ServiceManagement/SubscriberList/SubscriberList.js
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
  core/src/main/java/com/alibaba/nacos/core/service/NamespaceOperationService.java
  core/src/test/java/com/alibaba/nacos/core/service/NamespaceOperationServiceTest.java
Labels: kind/refactor
