Repository alibaba/nacos, pull requests merged in 2024-09, with the labels that each got.

#12573 [Refactor&Enhancement] Enhance naming server status check.
  consistency/src/main/java/com/alibaba/nacos/consistency/ConsistencyProtocol.java
  core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocol.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/JRaftServer.java
  core/src/main/java/com/alibaba/nacos/core/distributed/raft/RaftConfig.java
  core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftProtocolTest.java
  core/src/test/java/com/alibaba/nacos/core/distributed/raft/JRaftServerTest.java
  naming/src/main/java/com/alibaba/nacos/naming/cluster/ServerStatusManager.java
  naming/src/main/java/com/alibaba/nacos/naming/web/TrafficReviseFilter.java
  naming/src/test/java/com/alibaba/nacos/naming/cluster/ServerStatusManagerTest.java
Labels: kind/enhancement, kind/bug, kind/refactor

#12575 Addition for #12563, Add parameter check for tag.
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeBatchListenRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigChangeClusterSyncRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/service/dump/disk/ConfigRawDiskService.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/disk/ConfigRawDiskServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/ParamUtilsTest.java
Labels: kind/bug

#12574 [ISSUE #12555] SwitchManager support http、tcp、mysql HealthParams and pushCSharpVersion update
  naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchEntry.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/SwitchManager.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/UpdateSwitchForm.java
Labels: kind/enhancement, area/Naming

#12578 [ISSUE#12547] nacos client supports desensitise in logging.
  client/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
  client/src/main/java/com/alibaba/nacos/client/utils/ParamUtil.java
  client/src/test/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessorTest.java
  client/src/test/java/com/alibaba/nacos/client/utils/ParamUtilTest.java
Labels: kind/enhancement, area/Client

#12582 [Issue#12569] Enhance is exist table logic to support more database.
  core/src/main/java/com/alibaba/nacos/core/namespace/repository/EmbeddedNamespacePersistServiceImpl.java
  core/src/main/java/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceImpl.java
  core/src/test/java/com/alibaba/nacos/core/namespace/repository/EmbeddedNamespacePersistServiceTest.java
  core/src/test/java/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceTest.java
Labels: kind/enhancement, plugin

#12584 [ISSUE#12583] ProtocolManager代码优化
  core/src/main/java/com/alibaba/nacos/core/distributed/ProtocolManager.java
Labels: kind/enhancement

#12553 [ISSUE #12017] Add the console backend API for new section
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleHistoryController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleClusterController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleInstanceController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/naming/ConsoleServiceController.java
  console/src/main/java/com/alibaba/nacos/console/handler/config/HistoryHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/core/ClusterHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/config/HistoryInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/core/ClusterInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/naming/InstanceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/naming/ServiceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/naming/InstanceHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/naming/ServiceHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/config/HistoryProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/ClusterProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/InstanceProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/ServiceProxy.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/PermissionControllerV3.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/RoleControllerV3.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/UserControllerV3.java
Labels: Summer

#12591 [ISSUE #12017] Add the console backend API for old section
  console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleHealthController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/ConsoleServerStateController.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/core/ConsoleNamespaceController.java
  console/src/main/java/com/alibaba/nacos/console/handler/HealthHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/ServerStateHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/core/NamespaceHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/HealthInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/ServerStateInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/core/NamespaceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/HealthProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/ServerStateProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/NamespaceProxy.java
Labels: Summer

#12596 Upgrade spring to 5.3.39 and tomcat to 9.0.93
  pom.xml
Labels: dependencies

#12604 fix labels from env
  common/src/main/java/com/alibaba/nacos/common/labels/impl/DefaultLabelsCollector.java
Labels: area/Config

#12610 Fix wrong error code for http open api request.
  config/src/main/java/com/alibaba/nacos/config/server/exception/GlobalExceptionHandler.java
  naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java
  pom.xml
Labels: kind/enhancement

#12659 fix derby usage filed
  config/src/main/java/com/alibaba/nacos/config/server/service/NamespaceConfigInfoService.java
  config/src/test/java/com/alibaba/nacos/config/server/service/NamespaceConfigInfoServiceTest.java
Labels: kind/bug, plugin

#12671 fix #12670: can't login when domain like 'register.nacos.com', ie. contains …
  console-ui/src/utils/request.js
  console/src/main/resources/static/js/main.js
Labels: kind/bug, area/Nacos console
