Repository alibaba/nacos, pull requests merged in 2024-08, with the labels that each got.

#12449 [ISSUE #12342] Resolve the Hessian package conflict issue.
  consistency/pom.xml
  pom.xml
Labels: dependencies

#12490 [Enhancement] Enhance derby sql to support limit sql.
  core/src/main/java/com/alibaba/nacos/core/persistence/DistributedDatabaseOperateImpl.java
  persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/operate/StandaloneDatabaseOperateImpl.java
  persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/sql/limiter/SqlLimiter.java
  persistence/src/main/java/com/alibaba/nacos/persistence/repository/embedded/sql/limiter/SqlTypeLimiter.java
  persistence/src/test/java/com/alibaba/nacos/persistence/repository/embedded/operate/StandaloneDatabaseOperateImplTest.java
  persistence/src/test/java/com/alibaba/nacos/persistence/repository/embedded/sql/limiter/SqlTypeLimiterTest.java
Labels: kind/enhancement

#12492 V1.x develop limit storage
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/DistributedDatabaseOperateImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/StandaloneDatabaseOperateImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/sql/limit/SqlLimiter.java
  config/src/main/java/com/alibaba/nacos/config/server/service/sql/limit/SqlTypeLimiter.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/KeyBuilder.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/impl/BasePersistentServiceProcessor.java
Labels: kind/refactor

#12510 [ISSUE #12509] Fix nacos-client updating accessToken bug.
  client/src/main/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImpl.java
Labels: kind/bug, plugin

#12491 [ISSUE #12483] Configuration list adds configuration format
  common/src/main/java/com/alibaba/nacos/common/constant/Symbols.java
  config/src/main/java/com/alibaba/nacos/config/server/constant/ParametersField.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java
  console-ui/README.md
  console-ui/package.json
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js
  console/README.md
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/derby/ConfigInfoTagsRelationMapperByDerby.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigInfoMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/impl/mysql/ConfigTagsRelationMapperByMySql.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigInfoMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ConfigTagsRelationMapper.java
  plugin/datasource/src/main/java/com/alibaba/nacos/plugin/datasource/mapper/ext/WhereBuilder.java
Labels: kind/enhancement, area/Nacos console

#12420 [ISSUE #12017] Add console backend configuration handling
  auth/src/main/java/com/alibaba/nacos/auth/annotation/Secured.java
  console/src/main/java/com/alibaba/nacos/console/config/ConsoleConfig.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigController.java
  console/src/main/java/com/alibaba/nacos/console/handler/config/ConfigHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/inner/config/ConfigInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java
  console/src/main/resources/application.properties
  console/src/test/java/com/alibaba/nacos/console/controller/v3/config/ConsoleConfigControllerTest.java
  plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/constant/ApiType.java
Labels: Summer

#12564 [ISSUE#12563] Fix paramchecker invalid bug
  core/src/main/java/com/alibaba/nacos/core/paramcheck/CheckConfiguration.java
  core/src/test/java/com/alibaba/nacos/core/paramcheck/CheckConfigurationTest.java
Labels: kind/bug

#12565 Revert "Resolve the Hessian package conflict issue. (#12449)"
  consistency/pom.xml
  pom.xml
Labels: dependencies
