Repository alibaba/nacos, pull requests merged in 2024-07, with the labels that each got.

#12239 [ISSUE #12196] FIX prometheus http sd invalid label names
  prometheus/src/main/java/com/alibaba/nacos/prometheus/utils/PrometheusUtils.java
Labels: kind/bug, plugin

#12220 [ISSUE #12219] 修复nacos-client中config的ServerListManager解析endpoint失败问题
  client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java
  client/src/test/java/com/alibaba/nacos/client/config/impl/ServerListManagerTest.java
Labels: kind/bug, area/Client

#12318 add some UT for default auth plugin
  auth/src/test/java/com/alibaba/nacos/auth/config/AuthModuleStateBuilderTest.java
  auth/src/test/java/com/alibaba/nacos/auth/mock/MockAuthPluginServiceB.java
  auth/src/test/resources/META-INF/services/com.alibaba.nacos.plugin.auth.spi.server.AuthPluginService
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/authenticate/AbstractAuthenticationManagerTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/authenticate/LdapAuthenticationManagerTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/PermissionControllerTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/RoleControllerTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
Labels: area/Test

#12325 [ISSUE #12321] fix unexpect exception from NetworkInterface.ifUp
  sys/src/main/java/com/alibaba/nacos/sys/utils/InetUtils.java
  sys/src/test/java/com/alibaba/nacos/sys/utils/InetUtilsTest.java
Labels: kind/enhancement

#12353 [ISSUE #12221]Remove the accessToken from the URL.
  console-ui/src/globalLib.js
  console-ui/src/utils/request.js
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: kind/enhancement

#12350 Adjust integration tests for cluster,code,smoke modules in the core module to comply with checkstyle.
  test/core-test/src/test/java/com/alibaba/nacos/test/core/SnowFlowerIdGeneratorCoreITCase.java
  test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/MemberLookupCoreITCase.java
  test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/ServerMemberManagerCoreITCase.java
  test/core-test/src/test/java/com/alibaba/nacos/test/core/code/ControllerMethodsCacheCoreITCase.java
  test/core-test/src/test/java/com/alibaba/nacos/test/smoke/NacosSmokeCoreITCase.java
Labels: area/Test

#12369 Upgrade grpc to 1.64.2
  api/pom.xml
  core/pom.xml
  pom.xml
Labels: dependencies

#12372 Close derby ops api default.
  config/src/main/java/com/alibaba/nacos/config/server/configuration/ConfigCommonConfig.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigOpsController.java
  config/src/test/java/com/alibaba/nacos/config/server/configuration/ConfigCommonConfigTest.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/ConfigOpsControllerTest.java
  test/config-test/src/test/java/com/alibaba/nacos/test/base/BaseClusterTest.java
  test/config-test/src/test/java/com/alibaba/nacos/test/config/ConfigDerbyRaft_DITCase.java
Labels: kind/enhancement

#12382 Develop support ram info switch
  .gitignore
  api/src/main/java/com/alibaba/nacos/api/PropertyKeyConst.java
  api/src/main/java/com/alibaba/nacos/api/SystemPropertyKeyConst.java
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  client/src/main/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImpl.java
  client/src/main/java/com/alibaba/nacos/client/auth/ram/utils/RamUtil.java
  client/src/test/java/com/alibaba/nacos/client/auth/ram/utils/RamUtilTest.java
  pom.xml
Labels: kind/enhancement

#12396 Revert "Add an id primary key column to both the roles and permission…
  config/src/main/resources/META-INF/mysql-schema.sql
  distribution/conf/mysql-schema.sql
Labels: kind/bug, plugin

#12398 Fix #12395, use request context replace session depend.
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/controller/UserControllerTest.java
Labels: kind/bug, plugin

#12399 [ISSUE #12397]Fix the bug of ConnectionControlManager,use RuleParser to create a blank rule
  plugin/control/src/main/java/com/alibaba/nacos/plugin/control/connection/ConnectionControlManager.java
Labels: kind/bug, plugin
