Repository alibaba/nacos, pull requests merged in 2025-01, with the labels that each got.

#13007 V3.0 develop fix console login problem
  console-ui/src/reducers/authority.js
  console/src/main/java/com/alibaba/nacos/console/config/ConsoleWebConfig.java
  console/src/main/java/com/alibaba/nacos/console/config/NacosConsoleAuthControllerConfig.java
  console/src/main/java/com/alibaba/nacos/console/proxy/HealthProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/config/HistoryProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/ClusterProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/NamespaceProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/InstanceProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/ServiceProxy.java
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/CustomAuthenticationProvider.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/JwtAuthenticationEntryPoint.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/NacosAuthPluginConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/NacosAuthPluginWebConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/PermissionController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/PermissionControllerV3.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/filter/JwtAuthenticationTokenFilter.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/ldap/LdapAuthPluginConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/ldap/LdapAuthenticationProvider.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/ldap/NacosLdapContextSource.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/TokenManagerDelegate.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/CachedJwtTokenManager.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/token/impl/JwtTokenManager.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/ldap/LdapAuthenticationProviderTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/token/impl/CachedJwtTokenManagerTest.java
Labels: Nacos3.0

#13009 V3.0 develop enhancement configuration file and fix deploy problem
  bootstrap/pom.xml
  bootstrap/src/main/java/com/alibaba/nacos/bootstrap/NacosBootstrap.java
  bootstrap/src/main/resources/application.properties
  console/pom.xml
  distribution/bin/startup.cmd
  distribution/bin/startup.sh
  distribution/conf/application.properties
  distribution/conf/application.properties.example
  distribution/pom.xml
  distribution/release-config.xml
  distribution/release-core.xml
  distribution/release-nacos.xml
  distribution/release-naming.xml
  lock/src/test/java/com/alibaba/nacos/lock/service/impl/LockOperationServiceImplTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/ldap/LdapAuthenticationProviderTest.java
  pom.xml
Labels: Nacos3.0

#13011 V3.0 develop add condition for console request handler
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/EnabledInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/HealthInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/ServerStateInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/ConfigInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/config/HistoryInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/core/ClusterInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/core/NamespaceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/naming/InstanceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/naming/ServiceInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/EnabledRemoteHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/HealthProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/ServerStateProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/config/ConfigProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/config/HistoryProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/ClusterProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/NamespaceProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/InstanceProxy.java
  console/src/main/java/com/alibaba/nacos/console/proxy/naming/ServiceProxy.java
Labels: kind/refactor, Nacos3.0

#12950 [ISSUE #12946] Improve Clarity and Log Level of Shutdown Message in HttpClientBeanHolder
  client/src/main/java/com/alibaba/nacos/client/config/impl/ConfigHttpClientManager.java
  client/src/main/java/com/alibaba/nacos/client/naming/remote/http/NamingHttpClientManager.java
  common/src/main/java/com/alibaba/nacos/common/executor/ThreadPoolManager.java
  common/src/main/java/com/alibaba/nacos/common/http/HttpClientBeanHolder.java
  common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/HttpClientManager.java
  naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClientManager.java
Labels: kind/enhancement, area/Client

#13029 Fix running problem after upgrade to spring boot 3
  client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java
  common/src/test/java/com/alibaba/nacos/common/utils/FuzzyGroupKeyPatternTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/MD5UtilTest.java
  console/pom.xml
  naming/src/test/java/com/alibaba/nacos/naming/core/v2/index/ClientServiceIndexesManagerTest.java
Labels: Nacos3.0

#13022 [ISSUE#13021] fix comment typo on ServiceInfo(key) constructor
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
Labels: kind/code quality

#13035 Upgrade 2.5.0 and bump console-ui dependencies by npm audix.
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllProcessorTest.java
  console-ui/package-lock.json
  naming/src/test/java/com/alibaba/nacos/naming/controllers/ServiceControllerTest.java
  pom.xml
  sys/src/test/java/com/alibaba/nacos/sys/env/EnvUtilTest.java
Labels: dependencies

#13044 V3.0 develop admin adi enhance and refactor.
  common/src/main/java/com/alibaba/nacos/common/Beta.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ListenerControllerV3.java
  config/src/main/java/com/alibaba/nacos/config/server/model/form/ConfigForm.java
  config/src/test/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3Test.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/CoreOpsControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/model/response/ServerLoaderMetrics.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ClientControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperator.java
  naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Operator.java
  naming/src/main/java/com/alibaba/nacos/naming/model/form/ClientServiceForm.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3Test.java
Labels: Nacos3.0

#13052 Specified nacos-client and dependencies to java 8.
  api/pom.xml
  client/pom.xml
  common/pom.xml
  common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java
  config/src/test/java/com/alibaba/nacos/config/server/model/ConfigCachePostProcessorDelegateTest.java
  config/src/test/java/com/alibaba/nacos/config/server/service/ConfigFuzzyWatchContextServiceTest.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/Md5ComparatorDelegateTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/compatibility/ApiCompatibilityConfigTest.java
  logger-adapter-impl/log4j2-adapter/pom.xml
  logger-adapter-impl/logback-adapter-12/pom.xml
  plugin/auth/pom.xml
  plugin/encryption/pom.xml
  pom.xml
Labels: Nacos3.0

#13046 [ISSUE #12823] Randomly generate TokenRefreshWindow
  client/src/main/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImpl.java
  client/src/test/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImplTest.java
Labels: kind/enhancement, area/Client, plugin

#13071 [ISSUE#13067] Fix prometheus auth manager problem.
  console/src/main/java/com/alibaba/nacos/console/config/ConsoleWebConfig.java
  console/src/main/java/com/alibaba/nacos/console/handler/config/ConfigHandler.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/NacosAuthPluginWebConfig.java
  prometheus/src/main/java/com/alibaba/nacos/prometheus/conf/PrometheusSecurityConfiguration.java
  prometheus/src/main/java/com/alibaba/nacos/prometheus/filter/PrometheusAuthFilter.java
Labels: kind/bug, Nacos3.0
