Repository alibaba/nacos, pull requests merged in 2025-09, with the labels that each got.

#13768 [ISSUE #13767] fix: service NullPointerException when getSpec()
  k8s-sync/src/main/java/com/alibaba/nacos/k8s/sync/K8sSyncServer.java
Labels: kind/bug, area/Kubernetes

#13764 [ISSUE #13761]Fix: Add validation when deleting roles to prevent issues like mistakenly deleting ROLE_ADMIN.
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceDirectImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceRemoteImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceDirectImplTest.java
Labels: kind/enhancement, area/plugin

#13759 issue13423
  ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/AI/McpManagement/McpManagement.js
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: kind/enhancement, area/Nacos console, area/MCP

#13785 [ISSUE#13322] Add agent name codec.
  ai/src/main/java/com/alibaba/nacos/ai/service/A2aServerOperationService.java
  config/src/main/java/com/alibaba/nacos/config/server/utils/ParamUtils.java
  config/src/test/java/com/alibaba/nacos/config/server/utils/ParamUtilsTest.java
Labels: kind/feature

#13793 [ISSUE#13322] Refactor a2a admin and console api implementation.
  ai/src/main/java/com/alibaba/nacos/ai/controller/A2aAdminController.java
  ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentCardForm.java
  ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentCardUpdateForm.java
  ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentForm.java
  ai/src/main/java/com/alibaba/nacos/ai/form/a2a/admin/AgentListForm.java
  ai/src/main/java/com/alibaba/nacos/ai/service/A2aServerOperationService.java
  ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
  ai/src/main/java/com/alibaba/nacos/ai/service/SimpleSyncEffectService.java
  ai/src/main/java/com/alibaba/nacos/ai/service/SyncEffectService.java
  ai/src/main/java/com/alibaba/nacos/ai/utils/AgentCardUtil.java
  ai/src/main/java/com/alibaba/nacos/ai/utils/AgentRequestUtil.java
  ai/src/test/java/com/alibaba/nacos/ai/service/McpServerOperationServiceTest.java
  ai/src/test/java/com/alibaba/nacos/ai/service/SimpleSyncEffectServiceTest.java
  ai/src/test/java/com/alibaba/nacos/ai/service/SyncEffectServiceTest.java
  api/src/main/java/com/alibaba/nacos/api/ai/constant/AiConstants.java
  console-ui/src/pages/AI/NewAgent/NewAgent.js
  console/src/main/java/com/alibaba/nacos/console/controller/v3/ai/ConsoleA2aController.java
  console/src/main/java/com/alibaba/nacos/console/handler/ai/A2aHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/ai/A2aInnerHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/noop/ai/A2aNoopHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/ai/A2aRemoteHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/ai/A2aProxy.java
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/A2aMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/ai/NacosAiMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/constants/Constants.java
Labels: kind/feature, kind/refactor

#13812 [ISSUE #13810] 修复配置发布时 Derby 和 MySQL 数据库表现不一致的Bug
  config/src/main/java/com/alibaba/nacos/config/server/service/ConfigOperationService.java
  config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImpl.java
  config/src/test/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedConfigInfoPersistServiceImplTest.java
Labels: kind/bug, area/Config

#13826 Add a2a api auth resource parser.
  auth/src/main/java/com/alibaba/nacos/auth/GrpcProtocolAuthService.java
  auth/src/main/java/com/alibaba/nacos/auth/parser/grpc/AiGrpcResourceParser.java
  auth/src/main/java/com/alibaba/nacos/auth/parser/http/AiHttpResourceParser.java
Labels: kind/feature

#13831 fix: Upgrade jraft to 1.3.15.bugfix
  pom.xml
Labels: dependencies

#13872 [ISSUE #13869] fix Error creating bean with name 'consoleHealthContro…
  console/src/main/java/com/alibaba/nacos/console/handler/impl/inner/EnabledInnerHandler.java
Labels: kind/enhancement
