Repository alibaba/nacos, pull requests merged in 2025-05, with the labels that each got.

#13348 Add init password hints.
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/Register/Register.jsx
  console-ui/src/pages/Register/index.scss
  console/src/main/resources/static/css/main.css
  console/src/main/resources/static/index.html
  console/src/main/resources/static/js/main.js
Labels: kind/enhancement, area/Nacos console

#13388 [ISSUE#13321] Fix prometheus metrics api can't accept.
  bootstrap/src/main/resources/application.properties
  config/pom.xml
  config/src/test/java/com/alibaba/nacos/config/server/service/dump/processor/DumpAllGrayProcessorTest.java
  core/pom.xml
  core/src/test/java/com/alibaba/nacos/core/config/AuthModuleStateBuilderTest.java
Labels: kind/bug

#13394 [ISSUE #13273]: 2.x support create cluseter client use nacos.remote.client.grpc config
  common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClientFactory.java
  common/src/test/java/com/alibaba/nacos/common/remote/client/RpcClientFactoryTest.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java
Labels: kind/bug

#13444 Add ai module unit test and fix found bug.
  .github/workflows/ci.yml
  ai/pom.xml
  ai/src/main/java/com/alibaba/nacos/ai/index/PlainMcpServerIndex.java
  ai/src/main/java/com/alibaba/nacos/ai/service/McpDefaultNamespaceService.java
  ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
  ai/src/test/java/com/alibaba/nacos/ai/config/McpConfigurationTest.java
  ai/src/test/java/com/alibaba/nacos/ai/controller/McpAdminControllerTest.java
  ai/src/test/java/com/alibaba/nacos/ai/index/PlainMcpServerIndexTest.java
  ai/src/test/java/com/alibaba/nacos/ai/param/McpHttpParamExtractorTest.java
  ai/src/test/java/com/alibaba/nacos/ai/service/McpEndpointOperationServiceTest.java
  ai/src/test/java/com/alibaba/nacos/ai/service/McpServerOperationServiceTest.java
  ai/src/test/java/com/alibaba/nacos/ai/service/McpToolOperationServiceTest.java
  ai/src/test/java/com/alibaba/nacos/ai/utils/McpConfigUtilsTest.java
  ai/src/test/java/com/alibaba/nacos/ai/utils/McpProtocolUtilsTest.java
  ai/src/test/java/com/alibaba/nacos/ai/utils/McpRequestUtilTest.java
  console/src/test/java/com/alibaba/nacos/console/handler/impl/remote/config/ConfigImportAndExportServiceTest.java
  pom.xml
Labels: kind/bug, area/Test

#13452 [ISSUE#13445] Change some data relation admin api to normal user access.
  api/src/main/java/com/alibaba/nacos/api/common/Constants.java
  auth/src/main/java/com/alibaba/nacos/auth/parser/http/ConfigHttpResourceParser.java
  auth/src/test/java/com/alibaba/nacos/auth/HttpProtocolAuthServiceTest.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/HistoryControllerV3.java
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ListenerControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ClientControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ClusterControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/HealthControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3.java
Labels: kind/enhancement
