Repository alibaba/nacos, pull requests merged in 2025-04, with the labels that each got.

#13218 Fix naming v1 catalog page service api return all datum when pageSize…
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
Labels: kind/bug, area/Naming

#13225 Remove /node/self/health API & Fix stop beta action type.
  config/src/main/java/com/alibaba/nacos/config/server/controller/v3/ConfigControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
Labels: Nacos3.0

#13257 Add mcp admin api.
  ai/src/main/java/com/alibaba/nacos/ai/config/McpConfiguration.java
  ai/src/main/java/com/alibaba/nacos/ai/controller/McpController.java
  ai/src/main/java/com/alibaba/nacos/ai/model/mcp/McpServerStorageInfo.java
  ai/src/main/java/com/alibaba/nacos/ai/param/McpHttpParamExtractor.java
  ai/src/main/java/com/alibaba/nacos/ai/service/McpServerOperationService.java
  ai/src/main/java/com/alibaba/nacos/ai/service/McpToolOperationService.java
  ai/src/main/java/com/alibaba/nacos/ai/utils/McpRequestUtil.java
  ai/src/main/resources/META-INF/services/com.alibaba.nacos.core.paramcheck.AbstractHttpParamExtractor
  api/src/main/java/com/alibaba/nacos/api/ai/model/mcp/McpServerBasicInfo.java
  common/src/main/java/com/alibaba/nacos/common/paramcheck/DefaultParamChecker.java
  common/src/main/java/com/alibaba/nacos/common/paramcheck/ParamInfo.java
  common/src/test/java/com/alibaba/nacos/common/paramcheck/DefaultParamCheckerTest.java
  console/src/main/java/com/alibaba/nacos/console/NacosConsoleStartUp.java
  console/src/main/java/com/alibaba/nacos/console/controller/v3/ai/ConsoleMcpController.java
  console/src/main/java/com/alibaba/nacos/console/paramcheck/ConsoleDefaultHttpParamExtractor.java
  console/src/test/java/com/alibaba/nacos/console/NacosConsoleStartUpTest.java
  console/src/test/java/com/alibaba/nacos/console/cluster/RemoteServerMemberManagerTest.java
  console/src/test/java/com/alibaba/nacos/console/config/ConsoleAuthModuleStateBuilderTest.java
  console/src/test/java/com/alibaba/nacos/console/config/ConsoleDeploymentConfigTest.java
  console/src/test/java/com/alibaba/nacos/console/config/ConsoleModuleStateBuilderTest.java
  console/src/test/java/com/alibaba/nacos/console/config/ConsoleWebConfigTest.java
  console/src/test/java/com/alibaba/nacos/console/config/NacosConsoleAuthConfigTest.java
  console/src/test/java/com/alibaba/nacos/console/config/NacosConsoleBeanPostProcessorConfigurationTest.java
  console/src/test/java/com/alibaba/nacos/console/exception/ConsoleExceptionHandlerTest.java
  console/src/test/java/com/alibaba/nacos/console/exception/NacosApiExceptionHandlerTest.java
  console/src/test/java/com/alibaba/nacos/console/filter/NacosConsoleAuthFilterTest.java
  console/src/test/java/com/alibaba/nacos/console/handler/impl/AbstractServerStateHandlerTest.java
  console/src/test/java/com/alibaba/nacos/console/paramcheck/ConsoleDefaultHttpParamExtractorTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/HealthProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/ServerStateProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/ai/McpProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/config/ConfigProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/config/HistoryProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/core/ClusterProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/core/NamespaceProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/naming/InstanceProxyTest.java
  console/src/test/java/com/alibaba/nacos/console/proxy/naming/ServiceProxyTest.java
  console/src/test/resources/mock/application.properties
  console/src/test/resources/mock/existconf/announcement_zh_CN.conf
  console/src/test/resources/mock/existconf/console-guide.conf
  core/src/test/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3Test.java
Labels: kind/feature, Nacos3.0

#13278 Aipage
  console-ui/src/globalLib.js
  console-ui/src/index.js
  console-ui/src/layouts/menu.js
  console-ui/src/locales/en-US.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/AI/McpDetail/CreateTools/DeleteTool.js
  console-ui/src/pages/AI/McpDetail/CreateTools/components.js
  console-ui/src/pages/AI/McpDetail/CreateTools/index.js
  console-ui/src/pages/AI/McpDetail/McpDetail.js
  console-ui/src/pages/AI/McpDetail/index.js
  console-ui/src/pages/AI/McpManagement/DashboardCard.js
  console-ui/src/pages/AI/McpManagement/McpManagement.js
  console-ui/src/pages/AI/McpManagement/index.js
  console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
  console-ui/src/pages/AI/NewMcpServer/index.js
  console-ui/src/pages/AI/README.md
  console-ui/src/pages/ServiceManagement/ServiceDetail/EditServiceDialog.js
Labels: kind/feature, Nacos3.0

#13283 feat: 更新中文翻译，调整服务类型为协议类型；移除冗余后端协议字段；优化AI页面的命名空间列表和跳转逻辑
  console-ui/src/components/NameSpaceList/NameSpaceList.js
  console-ui/src/layouts/MainLayout.js
  console-ui/src/layouts/menu.js
  console-ui/src/locales/zh-CN.js
  console-ui/src/pages/AI/McpDetail/CreateTools/DeleteTool.js
  console-ui/src/pages/AI/McpDetail/CreateTools/index.js
  console-ui/src/pages/AI/McpDetail/McpDetail.js
  console-ui/src/pages/AI/McpManagement/McpManagement.js
  console-ui/src/pages/AI/NewMcpServer/NewMcpServer.js
Labels: kind/feature, Nacos3.0
