Repository alibaba/nacos, pull requests merged in 2025-02, with the labels that each got.

#13080 Support nacos console deployment independent: PR 2
  console/src/main/java/com/alibaba/nacos/console/cluster/RemoteServerMemberManager.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/core/ClusterRemoteHandler.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/cluster/NacosMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AbstractMemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/FileConfigMemberLookup.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/LookupFactory.java
  core/src/main/java/com/alibaba/nacos/core/cluster/lookup/StandaloneMemberLookup.java
Labels: Nacos3.0

#13087 Fix maintainer client some usage problem.
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/maintainer/ClusterInfo.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/maintainer/ServiceDetailInfo.java
  api/src/main/java/com/alibaba/nacos/api/selector/AbstractSelector.java
  api/src/test/java/com/alibaba/nacos/api/naming/pojo/maintainer/ServiceDetailInfoTest.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/ConfigMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/naming/IpAddressInfo.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/naming/Record.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/naming/SwitchDomain.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NamingMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxy.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/HttpClientManager.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/utils/ParamUtil.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImplTest.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImplTest.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxyTest.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/remote/HttpClientManagerTest.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ClusterInfo.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceDetailInfo.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/ServiceControllerV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/ServiceControllerV3Test.java
  naming/src/test/java/com/alibaba/nacos/naming/core/CatalogServiceV2ImplTest.java
Labels: Nacos3.0

#13089 [ISSUE#12979] Fix some api usage and move relatived VO to api module.
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/maintainer/InstanceMetadataBatchResult.java
  api/src/main/java/com/alibaba/nacos/api/naming/pojo/maintainer/MetricsInfo.java
  api/src/test/java/com/alibaba/nacos/api/naming/pojo/maintainer/InstanceMetadataBatchResultTest.java
  api/src/test/java/com/alibaba/nacos/api/naming/pojo/maintainer/MetricsInfoTest.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/naming/InstanceDetailInfoVo.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NamingMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxy.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImplTest.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxyTest.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/controllers/v3/OperatorControllerV3.java
  naming/src/main/java/com/alibaba/nacos/naming/core/Operator.java
  naming/src/main/java/com/alibaba/nacos/naming/model/vo/InstanceDetailInfoVo.java
  naming/src/main/java/com/alibaba/nacos/naming/model/vo/InstanceMetadataBatchOperationVo.java
  naming/src/main/java/com/alibaba/nacos/naming/model/vo/MetricsInfoVo.java
  naming/src/main/java/com/alibaba/nacos/naming/pojo/ServiceDetailInfo.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/InstanceControllerV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/InstanceControllerV3Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/OperatorControllerV3Test.java
Labels: Nacos3.0

#13095 [ISSUE#12979] Move core module relatived VO to api module.
  api/src/main/java/com/alibaba/nacos/api/common/NodeState.java
  api/src/main/java/com/alibaba/nacos/api/model/response/ConnectionInfo.java
  api/src/main/java/com/alibaba/nacos/api/model/response/ConnectionMetaInfo.java
  api/src/main/java/com/alibaba/nacos/api/model/response/IdGeneratorInfo.java
  api/src/main/java/com/alibaba/nacos/api/model/response/NacosMember.java
  api/src/main/java/com/alibaba/nacos/api/model/response/ServerLoaderMetric.java
  api/src/main/java/com/alibaba/nacos/api/model/response/ServerLoaderMetrics.java
  api/src/test/java/com/alibaba/nacos/api/model/response/ConnectionInfoTest.java
  api/src/test/java/com/alibaba/nacos/api/model/response/InstanceIdGeneratorInfoTest.java
  api/src/test/java/com/alibaba/nacos/api/model/response/NacosMemberTest.java
  api/src/test/java/com/alibaba/nacos/api/model/response/ServerLoaderMetricsTest.java
  config/src/main/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyService.java
  config/src/test/java/com/alibaba/nacos/config/server/service/notify/AsyncNotifyServiceTest.java
  core/src/main/java/com/alibaba/nacos/core/cluster/Member.java
  core/src/main/java/com/alibaba/nacos/core/cluster/MemberUtil.java
  core/src/main/java/com/alibaba/nacos/core/cluster/NodeState.java
  core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java
  core/src/main/java/com/alibaba/nacos/core/cluster/remote/MemberReportHandler.java
  core/src/main/java/com/alibaba/nacos/core/controller/NacosClusterController.java
  core/src/main/java/com/alibaba/nacos/core/controller/v2/CoreOpsV2Controller.java
  core/src/main/java/com/alibaba/nacos/core/controller/v2/NacosClusterControllerV2.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/CoreOpsControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3.java
  core/src/main/java/com/alibaba/nacos/core/remote/ConnectionMeta.java
  core/src/main/java/com/alibaba/nacos/core/remote/grpc/GrpcBiStreamRequestAcceptor.java
  core/src/main/java/com/alibaba/nacos/core/service/NacosClusterOperationService.java
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/MemberUtilTest.java
  core/src/test/java/com/alibaba/nacos/core/cluster/ServerMemberManagerTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/NacosClusterControllerTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/v2/CoreOpsV2ControllerTest.java
  core/src/test/java/com/alibaba/nacos/core/controller/v2/NacosClusterControllerV2Test.java
  core/src/test/java/com/alibaba/nacos/core/controller/v3/CoreOpsControllerV3Test.java
  core/src/test/java/com/alibaba/nacos/core/controller/v3/NacosClusterControllerV3Test.java
  core/src/test/java/com/alibaba/nacos/core/controller/v3/ServerLoaderControllerV3Test.java
  core/src/test/java/com/alibaba/nacos/core/remote/ConnectionTest.java
  core/src/test/java/com/alibaba/nacos/core/service/NacosClusterOperationServiceTest.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/ConfigMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/CoreMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/core/Connection.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/core/ConnectionMeta.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/core/IdGeneratorVO.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/core/Member.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/model/core/ServerLoaderMetrics.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImpl.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/naming/NamingMaintainerService.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/config/NacosConfigMaintainerServiceImplTest.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerServiceTest.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/naming/NacosNamingMaintainerServiceImplTest.java
  naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgent.java
  naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java
  naming/src/test/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientTransportAgentTest.java
  test/core-test/src/test/java/com/alibaba/nacos/test/core/cluster/ServerMemberManagerCoreITCase.java
Labels: Nacos3.0

#13094 [ISSUE #13093]fix bug of missing tansformation of namespace in config center
  config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigPublishRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
  config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigRemoveRequestHandler.java
  config/src/test/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandlerTest.java
Labels: kind/bug, area/Config

#13091 [ISSUE#13090] Compatible with v2 openapi to query configuration.
  config/src/main/java/com/alibaba/nacos/config/server/service/query/DefaultChainRequestExtractor.java
  config/src/test/java/com/alibaba/nacos/config/server/service/query/DefaultChainRequestExtractorTest.java
Labels: kind/bug, area/Config

#13107 [ISSUE #13106] Should resetConfig() in the constructor of TopNConfig.java
  core/src/main/java/com/alibaba/nacos/core/monitor/topn/TopNConfig.java
Labels: kind/bug, area/Nacos Core

#13101 [ISSUE#12979] Develop maintainer client auth service.
  client-basic/pom.xml
  client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/NacosAuthLoginConstant.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImpl.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/LoginProcessor.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImpl.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/RamConstants.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/RamContext.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialListener.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialService.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/CredentialWatcher.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/Credentials.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/IdentifyConstants.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/SpasCredential.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/SpasCredentialLoader.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/StsConfig.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/StsCredential.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/identify/StsCredentialHolder.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/injector/AbstractResourceInjector.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjector.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/injector/LockResourceInjector.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/injector/NamingResourceInjector.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/utils/CalculateV4SigningKeyUtil.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/utils/RamUtil.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/utils/SignUtil.java
  client-basic/src/main/java/com/alibaba/nacos/client/auth/ram/utils/SpasAdapter.java
  client-basic/src/main/java/com/alibaba/nacos/client/remote/HttpClientManager.java
  client-basic/src/main/resources/META-INF/services/com.alibaba.nacos.plugin.auth.spi.client.AbstractClientAuthService
  client-basic/src/test/java/com/alibaba/nacos/client/auth/impl/NacosClientAuthServiceImplTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessorTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/RamClientAuthServiceImplTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/identify/CredentialServiceTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/identify/CredentialWatcherTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/identify/CredentialsTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/identify/StsConfigTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/identify/StsCredentialHolderTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/injector/AbstractResourceInjectorTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/injector/ConfigResourceInjectorTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/injector/NamingResourceInjectorTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/utils/CalculateV4SigningKeyUtilTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/utils/RamUtilTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/utils/SignUtilTest.java
  client-basic/src/test/java/com/alibaba/nacos/client/auth/ram/utils/SpasAdapterTest.java
  client/pom.xml
  common/src/main/java/com/alibaba/nacos/common/model/RestResult.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxy.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/utils/ParamUtil.java
Labels: Nacos3.0

#13113 [ISSUE#13112] Develop admin API for namespaces.
  api/src/main/java/com/alibaba/nacos/api/model/response/Namespace.java
  console/src/main/java/com/alibaba/nacos/console/handler/core/NamespaceHandler.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/core/NamespaceRemoteHandler.java
  console/src/main/java/com/alibaba/nacos/console/proxy/core/NamespaceProxy.java
  core/src/main/java/com/alibaba/nacos/core/controller/v3/NamespaceControllerV3.java
  core/src/test/java/com/alibaba/nacos/core/controller/v3/NamespaceControllerV3Test.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/constants/Constants.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/CoreMaintainerService.java
  maintainer-client/src/test/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerServiceTest.java
  naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperator.java
Labels: Nacos3.0

#13136 Support callback service listeners anyway when listeners added.
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java
  client/src/main/java/com/alibaba/nacos/client/naming/selector/NamingListenerInvoker.java
  client/src/main/java/com/alibaba/nacos/client/selector/AbstractSelectorWrapper.java
  client/src/main/java/com/alibaba/nacos/client/selector/ListenerInvoker.java
  client/src/test/java/com/alibaba/nacos/client/naming/NacosNamingServiceTest.java
  pom.xml
Labels: kind/enhancement, area/Naming, area/Client

#13142 Refactor nacos default auth plugin to inject HTTP API by AutoConfiguration.
  api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java
  client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingMaintainService.java
  console/src/main/java/com/alibaba/nacos/console/cluster/RemoteServerMemberManager.java
  console/src/main/java/com/alibaba/nacos/console/config/ConsoleWebConfig.java
  console/src/main/java/com/alibaba/nacos/console/config/NacosConsoleAuthServiceConfig.java
  console/src/main/java/com/alibaba/nacos/console/handler/impl/remote/NacosMaintainerClientHolder.java
  console/src/test/java/com/alibaba/nacos/console/controller/ServerStateControllerTest.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/AbstractCoreMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/core/CoreMaintainerService.java
  maintainer-client/src/main/java/com/alibaba/nacos/maintainer/client/remote/ClientHttpProxy.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/OperatorControllerTest.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v2/OperatorControllerV2Test.java
  naming/src/test/java/com/alibaba/nacos/naming/controllers/v3/OperatorControllerV3Test.java
  plugin-default-impl/nacos-default-auth-plugin/pom.xml
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/condition/ConditionOnInnerDatasource.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/condition/ConditionOnLdapAuth.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/condition/ConditionOnNacosAuth.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/condition/ConditionOnRemoteDatasource.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/autoconfiguration/NacosAuthPluginInnerAutoConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/autoconfiguration/NacosAuthPluginRemoteAutoConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/core/NacosAuthPluginCoreConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/core/NacosAuthPluginInnerServiceConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/core/NacosAuthPluginRemoteServiceConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/persistence/NacosAuthPluginEmbeddedStorageConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/persistence/NacosAuthPluginExternalStorageConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/persistence/NacosAuthPluginPersistenceConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/web/NacosAuthPluginControllerConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/configuration/web/NacosAuthPluginWebConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/PermissionController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/RoleController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/UserController.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/PermissionControllerV3.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/RoleControllerV3.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/controller/v3/UserControllerV3.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/ldap/LdapAuthPluginConfig.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedPermissionPersistServiceImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedRolePersistServiceImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedUserPersistServiceImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalPermissionPersistServiceImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalRolePersistServiceImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/persistence/ExternalUserPersistServiceImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/AbstractCachedRoleService.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/AbstractCheckedRoleService.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceDirectImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/users/AbstractCachedUserService.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/java/com/alibaba/nacos/plugin/auth/impl/users/NacosUserServiceDirectImpl.java
  plugin-default-impl/nacos-default-auth-plugin/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/configuration/ConditionOnLdapAuthTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedPermissionPersistServiceImplTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedRolePersistServiceImplTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/persistence/EmbeddedUserPersistServiceImplTest.java
  plugin-default-impl/nacos-default-auth-plugin/src/test/java/com/alibaba/nacos/plugin/auth/impl/roles/NacosRoleServiceDirectImplTest.java
  server/src/main/java/com/alibaba/nacos/NacosServerBasicApplication.java
  server/src/main/java/com/alibaba/nacos/NacosServerWebApplication.java
  sys/src/main/java/com/alibaba/nacos/sys/env/Constants.java
Labels: kind/refactor, Nacos3.0
